### ISSUE TITLE
Issue: Minor issue with trying to install gsudo with Winget

### ISSUE THREAD

**Issue by pdjansse** [gerardog/gsudo#109]
## Issue Description
Minor issue with trying to install gsudo with Winget using the command in the read me. Using the command 'winget install gsudo' results in Winget finding another application from the Microsoft store. The command that should be in the readme is 'winget install gerardog.gsudo'

## Steps to Reproduce

1.  PS C:\> winget install gsudo

## Screenshots

![image](https://user-images.githubusercontent.com/78000532/136601046-2aff8fab-ed5d-4e97-a85d-0db99af2b249.png)

## Context:
 - Windows version: Windows 11 - Version 21H2 (OS Build 22000.194)
 - gsudo version: N/A

**Comment by gerardog** [comment]
This is a bug in microsoft/winget-cli#1574

Nonetheless I merged #110, so the readme shows a working command.

Thanks 🙏😊
