### ISSUE TITLE
Issue: Cannot switch to network drive when running gsudo

### ISSUE THREAD

**Issue by laundmo** [gerardog/gsudo#115]
## Issue Description

When opening a new shell using gsudo, switching to a network drive is not possible. I have not tested this with physical drives. `net use` returns that there are no mapped network drives, when in the shell started by gsudo. It returns the proper drives when outside gsudo.

## Steps to Reproduce
1. in cmd or powershell, run `gsudo cmd`, `sudo cmd`, `gsudo powershell` or `sudo powershell` 
2. attempt to navigate to a network mounted drive, in my case `G:`
3. observer the error about a drive with the name `G` not existing.

## Screenshots

![grafik](https://user-images.githubusercontent.com/24855949/140523986-ec82cd53-8dcd-4280-a7b7-e03f6286a50a.png)
(`Das System kann das angegebene Laufwerk nicht finden.` is german for "the system cant find the specified drive")
I did try with upercase drive letters too, although that really should not matter.

## Context:
 - Windows version: 21H1 19043.1288
 - gsudo version: gsudo v1.0.2 (Branch.master.Sha.cab27ed3ca23496129320dfed56624274c9a27a6)

**Comment by gerardog** [comment]
Hi, this is not gsudo's problem, but a windows known issue. Windows works that way intentionally. Right click on CMD and run as administrator without using gsudo, then try to connect to G: drive. You won't.

See the readme for reference:

> ## Known issues

> - The elevated instances do not have access to the network shares connected on the non-elevated space. This is not a `gsudo` issue but how Windows works. Use `--copyNS` to replicate Network Shares into the elevated session, but this is not bi-directional and it's interactive (may prompt for user/password).
