### ISSUE TITLE
Does it works in Windows Terminal? 

### ISSUE THREAD

**Issue by lssb** [gerardog/gsudo#116]
Does it works in Windows Terminal?  If yes, could you help me about how to develope a Windows Terminal Plugins? If there is a WIKI or guild?

**Comment by gerardog** [comment]
> Does it works in Windows Terminal? 
Gsudo? Yes.

> If yes, could you help me about how to develope a Windows Terminal Plugins? If there is a WIKI or guild?

I don't think there is a plug-in mechanism for WT.
What are you trying to build?
Maybe you should check WT source at https://github.com/microsoft/terminal

**Comment by lssb** [comment]
Thanks a lot for your response and  `Gsudo`. I will hava a try.
