### ISSUE TITLE
Issue: `gsudo -n` does not respect the Windows default terminal emulator

### ISSUE THREAD

**Issue by felipecrs** [gerardog/gsudo#117]
## Issue Description

The title should be self-explanatory. 😊

## Steps to Reproduce

1.  Windows 11 and Windows Terminal as default terminal emulator
2.  `gsudo -n`
![image](https://user-images.githubusercontent.com/29582865/140823837-fe003f2a-7763-4af7-b5a6-78945b85a195.png)

The conhost.exe is used even when default terminal emulator is Windows Terminal.

## Screenshots

![YgBLZasLED](https://user-images.githubusercontent.com/29582865/140824270-82e37e15-9257-4267-9321-7f912649867b.gif)

## Context:
 - Windows version: Windows 11 Pro 22000.282
 - gsudo version: 1.0.2

**Comment by gerardog** [comment]
Weird. What is going on here?

It looks like a Windows Terminal issue. See
microsoft/terminal#11564
microsoft/terminal#10276

Can't be fixed by gsudo. Can you do `gsudo wt.exe` instead?
Sorry.

**Comment by felipecrs** [comment]
Closing as it seems to be an issue with Windows Terminal as pointed by @gerardog.

Thank you very much for the response!
