### ISSUE TITLE
Question: Is there a way to provide the username for the uac prompt?

### ISSUE THREAD

**Issue by grafst** [gerardog/gsudo#120]

**Comment by gerardog** [comment]
No, sorry. gsdo relies on windows "RunAs verb" to elevate, which does not allow to pass a username 
But you can enable the cache to write your credentials once and elevate several times.

**Comment by grafst** [comment]
Ok, no worries. I love gsudo  and use it dozens of times  every day.

Am Do., 2. Dez. 2021 um 21:54 Uhr schrieb Gerardo Grignoli <
***@***.***>:
