### ISSUE TITLE
Issue: Installation from manuel by pwsh command didn't work

### ISSUE THREAD

**Issue by eIektro** [gerardog/gsudo#125]
## Issue Description

I c/p'ed below pwsh script to the my Windows Terminal runs PowerShell latest version. No response from shell and new line. When i type 'gsudo' to test. It does nothing and show default PowerShell not recognized error:

`gsudo: The term 'gsudo' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

 This script from the Manuel Installation section in the README.md.

```bash
PowerShell -Command "Set-ExecutionPolicy RemoteSigned -scope Process; iwr -useb https://raw.githubusercontent.com/gerardog/gsudo/master/installgsudo.ps1 | iex"
```

## Steps to Reproduce

1.  Open PowerShell
2.  Type line: `PowerShell -Command "Set-ExecutionPolicy RemoteSigned -scope Process; iwr -useb https://raw.githubusercontent.com/gerardog/gsudo/master/installgsudo.ps1 | iex"`
3. Run
4. Type `gsudo`

## Context:
 - Windows version: Windows 11 21H2 22000.434 

Thank for any response. <3

**Comment by gerardog** [comment]
This is how it should look like

<img width="947" alt="image" src="https://user-images.githubusercontent.com/3901474/150421764-cdde01a0-cb4e-4d88-95ba-4e4375e4567e.png">

Then, you should restart the console to refresh the PATH variable, to ensure gsudo is there.

If still not working try to paste the actual message received when running the command.

Thanks
