### ISSUE TITLE
How to view gsudo version

### ISSUE THREAD

**Issue by shuohao** [gerardog/gsudo#128]

**Comment by slobinger** [comment]
Do you mean  `gsudo --version` ?
```
gsudo --version
gsudo v1.1.0 (Branch.master.Sha.0575f14b40ff0fb3d5b799e7b4f5fc3f21df4d54)
Copyright(c) 2019-2021 Gerardo Grignoli and GitHub contributors
```

**Comment by shuohao** [comment]
> Do you mean `gsudo --version` ?
> 
> ```
> gsudo --version
> gsudo v1.1.0 (Branch.master.Sha.0575f14b40ff0fb3d5b799e7b4f5fc3f21df4d54)
> Copyright(c) 2019-2021 Gerardo Grignoli and GitHub contributors
> ```

![image](https://user-images.githubusercontent.com/4637107/157622653-8ece7129-35a8-457e-ab64-ec73098b4fe3.png)

yes  thank you
