### ISSUE TITLE
Issue: `gsudo notepad` won't open notepad on CMD / Win11 

### ISSUE THREAD

**Issue by gerardog** [gerardog/gsudo#131]
## Issue Description

`gsudo notepad` won't open notepad on CMD / Win11 

## Context:
 - Windows version: Win 11 21H2
 - gsudo version:      1.1.1

It seems like notepad is a Microsoft Store App now, and the detection for MS Store fails on this case.

**Comment by kristibektashi** [comment]
A workaround is to use `gsudo start notepad` instead.  This launches Notepad via the shell, which obviously works.
