### ISSUE TITLE
Issue: Windows 8.1: System.MissingMethodException: '!!0[] System.Array.Empty()'.

### ISSUE THREAD

**Issue by sebma** [gerardog/gsudo#132]
## Issue Description

Every `gsudo` calls fail with this exception : 
```powershell
PS C:\Users\ordi> gsudo -?

Exception non gérée : System.MissingMethodException: Méthode introuvable : '!!0[] System.Array.Empty()'.
   à gsudo.Helpers.ArgumentsHelper.GetRealCommandLine()
   à gsudo.Program.<Start>d__1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à gsudo.Program.<Main>d__0.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à gsudo.Program.<Main>()

```

## Steps to Reproduce

1.  type `gusdo -?`

## Screenshots

![image](https://user-images.githubusercontent.com/4569306/160608124-3efa742d-f044-49f5-aad0-9602888e8fe5.png)

## Context:
 - Windows version: 8.1 Pro [version 6.3.9600]
 - gsudo version:     1.2.0

**Comment by gerardog** [comment]
`gsudo` requires .NET 4.6, which is embedded on Win 10 & 11, but needs to be installed on a Window 8 machine.

Please install it. If you have Chocolatey, you can try: [`choco install dotnetfx`](https://community.chocolatey.org/packages/dotnetfx#description)

**Comment by gerardog** [comment]
Hi @sebma. Have you tried `choco install dotnetfx`? Did it worked? Did it fix the issue? 
Thanks

**Comment by sebma** [comment]
@gerardog [According to chocolatey, the dotnetfx package depends on KB2919355](https://community.chocolatey.org/packages/dotnetfx#dependencies) which fails to install.

**Comment by gerardog** [comment]
Please try: 
`choco install dotnetfx --ignoredependencies`
or
https://download.visualstudio.microsoft.com/download/pr/014120d7-d689-4305-befd-3cb711108212/0fd66638cde16859462a6243a4629a50/ndp48-x86-x64-allos-enu.exe

**Comment by gerardog** [comment]
@sebma, any update?

**Comment by sebma** [comment]
@gerardog Finally managed to install KB2919355 and dotnetfx, It was a C: partition free space pb.

Can you please add KB2919355 in the gsudo requirements for windows8 in your README.md ?

**Comment by gerardog** [comment]
Just found a very old Win7 Virtual Machine on my archive. Found interesting that windows update suggested the update of .NET 4.8.

![image](https://user-images.githubusercontent.com/3901474/164073946-d298f602-0cdf-4ebf-bab0-4d6fc56c0676.png)

Why not do that instead?

**Comment by gerardog** [comment]
Ok, tried Windows update. Really took a long time, and half the updates failed.
Then Windows Update stopped working. Installed KB2534111 which it was suppossed to fix the issue. Now Windows update takes all the memory (4gb because its an x86 img, then hangs)

**Comment by gerardog** [comment]
Got it working on Windows 7 SP1!
I downloaded Win7 from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

Steps:
- (probably optional) Install Google Chrome
- Enable TLS 1.2 [(download Microsoft "Easy Fix")
](https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392)
- Download [.NET Framework 4.8](https://dotnet.microsoft.com/download/dotnet-framework)

![image](https://user-images.githubusercontent.com/3901474/164116087-a2d668b4-8f99-4442-a132-d4965d657741.png)

**Comment by gerardog** [comment]
Tested W8.1.
- Download [.NET Framework 4.8](https://dotnet.microsoft.com/download/dotnet-framework)
- Download the `MSI` from github.

@sebma Using the newer Net Framework 4.8 installer from microsoft.com on both W7 and W8.1 is now simpler than installing choco and do not require manual installation of KB articles. I've updated the readme with this information. Thanks!
