### ISSUE TITLE
Issue: `bash -c "gsudo"` throws "Unauthorized." on git-bash/MinGw

### ISSUE THREAD

**Issue by gerardog** [gerardog/gsudo#134]
## Issue Description

Open git-bash or MinGW, run `bash -c "gsudo"`. It throws:
`Unauthorized. (Different gsudo.exe?) Error: Failed to substitute token. Connection from server lost.`

Instead run `bash -c "gsudo.exe"`, and it works.

May be rooted in FindExecutableInPath() function finding `gsudo` bash script in the path.

## Screenshots
https://twitter.com/TimMattison/status/1512109713101668352
https://www.notion.so/gsudo-testing-08a2bec5edad41838b199b3ed785435c

## Context:
 - Windows version: Win11
 - gsudo version:      1.2.0

**Comment by timmattison** [comment]
I have confirmed that `bash -c "gsudo.EXE ..."` works in my environment.

However, I have a bash script that I'm running that starts like this:

```
#!/usr/bin/env bash
```

And that script still fails even when using `gsudo.EXE`. You can recreate this without a script by doing this:

```
/usr/bin/env bash -c "gsudo.EXE ..."
```

That will still return the unauthorized error.

**Comment by timmattison** [comment]
Full command I tried was this:

```
gsudo.EXE 'powershell PsExec -s -i -d $env:VBOX_MSI_INSTALL_PATH\VirtualBox.exe'
```

**Comment by gerardog** [comment]
A quick follow up:

Both gsudo elevated service and non-elevated client where using different algorithms to find the invoker process (the one to allow in the credentials cache). This is one bug. 

The algorithm was manipulated (incorrectly) because I often find that git-bash / MinGW does not have a proper process tree on the window side (i.e. when you look at it in ProcessExplorer). An intermediate process ends prematurely leaving two independent process tree branches instead of only one.

<img width="775" alt="image" src="https://user-images.githubusercontent.com/3901474/162741463-f1fe32c6-d7d3-4d80-adb4-17de16c8dc52.png">

Please note missing Processes with id: 5060 & 20504. Shown in Process Explorer as independent process trees:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/3901474/162741707-87550a23-d69d-4338-a455-541f95666908.png">

<img width="414" alt="image" src="https://user-images.githubusercontent.com/3901474/162741586-634cef85-f9b8-4008-9ae4-183e1ff90900.png">

For some reason, this process "gap" ocurrs each time you call a bash script, like the `gsudo` wrapper for WSL that should have been harmless for MinGW but isn't.
 
This makes hard if not impossible to make the credentials cache. As it's security is based on allowing the parent process, but in this case the process is wrapped in short-lived `bash` instances. (each time the `gsudo` bash script is invoked, the root process is missing and the parent tree of `bash`s have different pids.

So, I don't think the cache can work on git-bash/MinGW. Every elevation would show a uac popup.

On the other side, `gsudo` should detect correctly (currently fails) the MinGW shell and interpret the command as a bash one, and run it as  `bash -c {command}` (unless `-d` specified). I will fix that too. Unfortunatelly to do that I need MinGW not to [translate](https://stackoverflow.com/questions/30473559/what-is-the-rule-of-msys-mingw-path-translation) all paths into Windows format (i.e.  `/mnt/c/` => `C:\`) which is something the problematic wrapper should do.

We can replace the wrapper with a bash function that doesn`t split the process tree, but that must be done in your `.bashrc` file.
```
gsudo() { 
gsudo.exe "$@" 
}
``` 

Haven't tested the function with the latest release. It may need the code I'm working on right now.

**Comment by gerardog** [comment]
Hi @timmattison, sorry it took a while to get a proper fix. 

What changed:
- If the process tree is intact (using gsudo.exe, or gsudo function()) the credentials cache should work (one uac popup for many elevations.
- If the process tree is splitted by MinGW (for example, by running a bash script), the cache wouldnt work, but the elevation should succeed (one uac popups per elevation)
- Also if you elevate a command it will be interpreted as a bash command: gsudo `ls /C/folder` will elevate as `bash -c "ls /C/folder"` instead of 'cmd /c ls C:\folder'

Could you please install a pre-release build and test it for a while?

From your screenshot I suspect you installed via winget, so first uninstall: `winget uninstall gerardog.gsudo`
Then install the prerelease with: `choco install gsudo --version=1.2.1-alpha10 --pre`

Alternatively: you can replace gsudo files with the (unsigned) [latest build](https://ci.appveyor.com/project/gerardog/gsudo/builds/43214702/artifacts) from the build server, to `C:\Program files(x86)\gsudo`

Thanks.

**Comment by timmattison** [comment]
I was on vacation so I didn't get a chance to try this yet. Appreciate the effort. I'll try it soon!

**Comment by gerardog** [comment]
Latest won't fail. Elevation will work.

But the cache won't work because the windows process tree splits when bash calls a bash script.
To also get the cache working, add this to your `.bash_rc`.

```bash
gsudo() { WSLENV=WSL_DISTRO_NAME:USER:$WSLENV MSYS_NO_PATHCONV=1 gsudo.exe "$@"; }
```

**Comment by gerardog** [comment]
I'm out of ideas on how to get the cache working, the MSYS2 argument conversion disabled, also working on WSL/CygWin/MSYS2/MinGW. 
The gsudo wrapper should do it, except it breaks process tree, hence the cache.
