### ISSUE TITLE
Feature: `gsudo --ti` to run as TrustedInstaller

### ISSUE THREAD

**Issue by xmrv** [gerardog/gsudo#136]
I know this has been discussed before but I'd like to come up with a couple examples as to why TI is a good addition and AV detection should not be a consideration.

- Users of such tools know how to deal with AVs and often uninstall them completely.
- Similar project nsudo (LC) offers TI without virustotal detection (longer syntax though).
- Some Windows registry keys related to customization need TI to change them (HKLM\Software\Microsoft\Windows\CurrentVersion\Control Panel\Settings\Network).

I am by no means a seasoned dev, just thought this would be a god tier tool if TI was an option.

**Comment by gerardog** [comment]
Thanks for your input. I understand that running as TI is useful for some audience.
If gsudo is flagged as virus by Microsoft Defender, or any top 5 av vendor, means game over for the project.

Whenever is ready will have to launch as pre-release for a while.

**Comment by gerardog** [comment]
How does "gsudo --ti" argument sound ?
Check out https://ci.appveyor.com/project/gerardog/gsudo/builds/43343399/artifacts

Replace your gsudo.exe folder contents with those artifacts.
Let me know if you tested it and any issue.

**Comment by xmrv** [comment]
Sounds good and it worked, thank you. Should I send false positive reports to AVs now or wait for a signed build or both?

**Comment by gerardog** [comment]
Do not submit to AV vendors yet. Let me review the code and I will release a signed build. I had trouble getting a TI token from Trustedinstaller service, so I used the SCHTASK method, but I still want to give it another try.

**Comment by gerardog** [comment]
Updated build artifacts:  
https://github.com/gerardog/gsudo/actions/runs/2989503528 (scroll down)

**Comment by xmrv** [comment]
First and most importantly, thank you.

The executables do not have a signiture when checked with sigcheck. So am I correct to assume I should still wait for the signed build for submission?

**Comment by gerardog** [comment]
The wait is almost over! I renewed the certificate this week. Later today or tomorrow.

**Comment by gerardog** [comment]
The new certificate needs to build up some reputation in order to avoid being flagged as potentially unwanted app.

![image](https://user-images.githubusercontent.com/3901474/188655226-7d6e9503-2794-4590-bcfb-6f9fe5bcbd30.png)

I've submitted v1.4.1 to Microsoft Defender...

![image](https://user-images.githubusercontent.com/3901474/188655435-b45846e3-2395-451e-a2af-81d33b567ff9.png)

But the warning still shows up.

**Comment by xmrv** [comment]
Using the guides [here](https://github.com/EmilyLove26/False-Positive-Reporter/wiki/How-to-Use) and [here](https://www.techsupportalert.com/how-to-report-malware-or-false-positives-to-multiple-antivirus-vendors/) I've submitted gsudo.exe to nearly 70 vendors in addition to a manual submission via Defender. 

<https://i.imgur.com/O7IdqNL.png>

<https://i.imgur.com/EvixEaX.png>

<https://i.imgur.com/avhaNxE.png>

**Comment by gerardog** [comment]
This feature has shipped in the v1.5.0 release. It will be marked as a pre-release for at least a few days until SmartScreen gathers enough "reputation". Please do not submit to av vendors, unless it is flagged as virus.
