### ISSUE TITLE
1.3.0 freeze on Windows 7/32bit starting procexp.exe

### ISSUE THREAD

**Issue by lazna** [gerardog/gsudo#137]
## Issue Description

gsudo start, ask for UAC password, accept it but, called program did not start. gsudo.exe process is present i memory twice with 0% CPU activity, console is blocked, CTRL+C dont help. Process must by killed via taskmanager.
Strange thing is, when --debug is included to command, Procexp.exe start normally....
## Steps to Reproduce

1.  on console window with user permission type "gsudo procexp.exe" and press enter
2. 
3. 

## Context:
 - Windows version: 7, 32bit
 - gsudo version:  1.3
- ProceXP 16.43 https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

**Comment by gerardog** [comment]
Tried it. It worked fine on my VM:
![image](https://user-images.githubusercontent.com/3901474/166994019-aa4b6206-a4b3-4169-a621-3280945b4c24.png)

However if you use Scoop to install SysInternals ProcExp.exe, the scoop-shim may take the console... and Ctrl-C is ignored.. But the ProcExp window still opens.

I suspect the UAC window is not showing, or showing on another desktop. Not sure.

Are you sure there is no UAC window hanging around?

If `--debug` breaks the test, use '--loglevel ALL' please.

**Comment by lazna** [comment]
Thats it! Freeze  as described....

```
C:\Users\ucetni>gsudo --loglevel ALL procexp
Debug: Command Line: --loglevel ALL procexp
Debug: Invoking Shell: Cmd
Debug: Command to run: "c:\utils\procexp.EXE"
Debug: Using Console mode Attached
Debug: Caller PID: 312
Debug: Caller SID: S-1-5-21-2827459849-1194722372-3822995680-1001
Debug: Elevating process: C:\utils\gsudo.exe gsudoelevate 312 S-1-5-21-2827459849-1194722372-3822995680-1001 All 00:00:0
0
Debug: Elevated instance started.
Debug: Connected via Named Pipe ProtectedPrefix\Administrators\gsudo_61BAB85F191CE24FD1C93BCA27C73D2BC792324D7B7B0C76AB4
670393B94A652.
Debug: ElevationRequest length 800
```

**Comment by gerardog** [comment]
This is probably caused by ProcExp (or it's shim) being both a console and a GUI app. Nonetheless It works for me. and to be honest, its looks hard to improve without specifying special logic for this specific app. Why not use `gsudo -n` instead and avoid the issue?
