### ISSUE TITLE
Issue: "gsudo/sudo !!" doesn't work properly

### ISSUE THREAD

**Issue by defaultunknown** [gerardog/gsudo#138]
## Issue Description

gsudo can't be used to execute previously used command that requires elevation using history substitution on powershell7.2.2.

## Steps to Reproduce

1.  Windows 11 Terminal powershell (version 7.2.2)
2.  Execute any command that requires elevation as regular user, for example: "net users test /add"
3.  Elevate most previous command with gsudo using "History substitution": "gsudo !!"

## Screenshots

![image](https://user-images.githubusercontent.com/44570919/167518698-7b47f09c-a63a-48d0-b987-390067e20bb9.png)
![image](https://user-images.githubusercontent.com/44570919/167518767-fabd572c-ca03-4791-ac62-9a225d615d75.png)

## Context:
 - Windows version: 21H2 (OS Build 22000.613)
 - gsudo version: gsudo v1.0.2 (Branch.master.Sha.cab27ed3ca23496129320dfed56624274c9a27a6)

**Comment by gerardog** [comment]
There was a problem with a missing file in older versions. Please update to v1.3.0, close your consoles to refresh the 'PATH' and test again.
