### ISSUE TITLE
Issue: BSOD on Windows 11 Beta Channel, when ran from a network drive

### ISSUE THREAD

**Issue by martinet101** [gerardog/gsudo#143]
## Issue Description

The issue occurs no matter the way in which gsudo is called. If the binary is stored in a network directory (ewither mapped or not), windows BSODs when the binary is ran.

The BSOD occurs after the UAC prompt, but running `gsudo -v` also causes the crash

## Steps to Reproduce

1.  Place gsudo in a network dir
2.  Run GSudo
3.  Enjoy your BSOD

## Screenshots
![image](https://user-images.githubusercontent.com/53119851/175815337-2433bd6f-046a-4e35-aace-cd26813cf61b.png)

## Context:
 - Windows version: Windows 11 22H1 (22621.160, on the beta channel)
 - gsudo version:      v1.3.0 (Branch.master.Sha.24fb735f547e1e5dd7aa22fdd77777fa8c923a1c)

**Comment by gerardog** [comment]
Hi @martinet101,
This is going to be hard to track as I don´t have a beta W11 at hand.

What kind of network drive are you connecting to? Windows Server 20XX? NAS? W10?

So this happens even on 'gsudo -v' which just shows the version... (i.e. when no elevation is involved). That rules out all the elevation modes.

Then, two possibilities come to my mind:

1. Maybe the Symbolic Link support ([1](https://github.com/gerardog/gsudo/blob/v1.3.0/src/gsudo/Program.cs#L12) [2](https://github.com/gerardog/gsudo/blob/v1.3.0/src/gsudo/Helpers/SymbolicLinkSupport.cs#L18))... 

2. Or, the usage of `ilmerge` to merge all build output files into one `gsudo.exe`... Can you test this [CI build](https://ci.appveyor.com/project/gerardog/gsudo/build/artifacts)? It has nothing special, except CI builds don't do the `ilmerge` step. Please do. I could then evaluate an alternative like gluck/il-repack

**Comment by martinet101** [comment]
The server is a samba server on a raspberry pi (raspbian 11 armhf)

**Comment by martinet101** [comment]
> 2\. Can you test this [CI build](https://ci.appveyor.com/project/gerardog/gsudo/build/artifacts)?

It works flawlessly

**Comment by martinet101** [comment]
> Keep in mind that the elevated context have an independent set of network connections. It may be the case that the elevated user can't access the samba share (does it requires user and password?), and then gsudo fails to load itself? This is pure speculation but I don't have the setup to test it.
> 
> You may want to be 100% sure that the elevated context has access (I mean an active connection) to the net share. For example: Run a CMD as administrator, access \server\share from the command line, for example `net use \\server\share`. To be sure, do `dir net use \\server\share\gsudo.exe` (always elevated). Then go back to non-admin and run gsudo. Does it BSOD?
> 
> I can imagine how infuriating BSOD´s are, but bear with me as this is not simple to diagnose, and less in spare time.

the release gsudo bsods no matter the way you invoke it.

**Comment by gerardog** [comment]
Hi again @martinet101,
I've just released gsudo [v1.4.0](https://github.com/gerardog/gsudo/releases/tag/v1.4.0).

This version uses `net7.0` single file publising, so it doesnt uses ilmerge. So it most certainly fixes this issue.
Nonetheless I would be happier if you could please update and confirm.

Thank you very much

**Comment by martinet101** [comment]
Yes, it does!

**Comment by martinet101** [comment]
Thank you!

**Comment by gerardog** [comment]
You are welcome!

**Comment by martinet101** [comment]
Hi @gerardog, version 1.7 appears to be affected by the same issue

**Comment by martinet101** [comment]
I just tried running it from the network drive and it straight crashed my pc with the same exact BSOD related avobe

**Comment by gerardog** [comment]
Damn!
v1.3 used ilmerge which I blamed, but v1.7 is packaged by dotnet self-contained NativeAOT...
This may be a windows problem... Elevation is problematic on network drives because elevated and unelevated sessions don't share network connections. So when you elevate the `%0`, the file may not be reacheable.

Of course I recommend you install gsudo on C: drive.
The thing is I don't have a raspberry pi, to mount a server.

Will see what I can do.

**Comment by gerardog** [comment]
Do you remember the steps?

**Comment by martinet101** [comment]
it was just
1. Place gsudo on a network drive
2. run and expect a crash






> The thing is I don't have a raspberry pi, to mount a server.

If you install WSL and then acces \\wsl.localhost you'll get a (kinda) network drive with wsl filesystem

**Comment by gerardog** [comment]
I have a network drive to test, but it's using a modern samba version, and not causing a restart.

![image](https://user-images.githubusercontent.com/3901474/193423979-3aa3bbfb-dddf-4e05-a832-2f7b23fff052.png)

Even tried in a loop elevating multiple times and the problem is not ocurring. Will keep testing

**Comment by martinet101** [comment]
Weird... i'll try further tests with other versions (1.6 and 1.5) and i'll let you know

**Comment by gerardog** [comment]
Other versions will fail as well.
How did you installed gsudo?
Are you using x64 version? Or .Net46?

**Comment by martinet101** [comment]
x64

**Comment by gerardog** [comment]
Can you do in Pwsh `{ Get-SmbConnection | fl }` as admin, and paste here the relevant connection? you can redact what's private.

**Comment by martinet101** [comment]
PS C:\Users\marti> sudo Get-SmbConnection | Select-Object -Property * | fl


Length : 0

Length : 102

Length : 102

Length : 102

Length : 102

Length : 102

Length : 102

Length : 102

Length : 0

Length : 0

**Comment by gerardog** [comment]
On PowerShell, sudo prefix is complicated.
If you already updated to `gsudo v1.6` (released 12 days ago) please try `sudo { Get-SmbConnection | Select-Object -Property * | fl }`.
I only need the relevant connection

**Comment by martinet101** [comment]
```
PS C:\Users\marti\scoop\apps\Gsudo\1.6.0> .\gsudo { Get-SmbConnection | Select-Object -Property * | fl }


SmbInstance           : Default
ContinuouslyAvailable : False
Credential            : MicrosoftAccount\marticlilop@gmail.com
Dialect               : 3.1.1
Encrypted             : False
NumOpens              : 1
Redirected            : False
ServerName            : samba-server
ShareName             : Abril
Signed                : False
UserName              : DESKTOP-TDSK6R6\marti
PSComputerName        :
CimClass              : ROOT/Microsoft/Windows/SMB:MSFT_SmbConnection
CimInstanceProperties : {ContinuouslyAvailable, Credential, Dialect, Encrypted...}
CimSystemProperties   : Microsoft.Management.Infrastructure.CimSystemProperties

SmbInstance           : Default
ContinuouslyAvailable : False
Credential            : MicrosoftAccount\marticlilop@gmail.com
Dialect               : 3.1.1
Encrypted             : False
NumOpens              : 1
Redirected            : False
ServerName            : samba-server
ShareName             : Marti
Signed                : False
UserName              : DESKTOP-TDSK6R6\marti
PSComputerName        :
CimClass              : ROOT/Microsoft/Windows/SMB:MSFT_SmbConnection
CimInstanceProperties : {ContinuouslyAvailable, Credential, Dialect, Encrypted...}
CimSystemProperties   : Microsoft.Management.Infrastructure.CimSystemProperties

SmbInstance           : Default
ContinuouslyAvailable : False
Credential            : MicrosoftAccount\marticlilop@gmail.com
Dialect               : 3.1.1
Encrypted             : False
NumOpens              : 1
Redirected            : False
ServerName            : samba-server
ShareName             : Software
Signed                : False
UserName              : DESKTOP-TDSK6R6\marti
PSComputerName        :
CimClass              : ROOT/Microsoft/Windows/SMB:MSFT_SmbConnection
CimInstanceProperties : {ContinuouslyAvailable, Credential, Dialect, Encrypted...}
CimSystemProperties   : Microsoft.Management.Infrastructure.CimSystemProperties

SmbInstance           : Default
ContinuouslyAvailable : False
Credential            : MicrosoftAccount\marticlilop@gmail.com
Dialect               : 3.1.1
Encrypted             : False
NumOpens              : 1
Redirected            : False
ServerName            : samba-server
ShareName             : SPTPrograms
Signed                : False
UserName              : DESKTOP-TDSK6R6\marti
PSComputerName        :
CimClass              : ROOT/Microsoft/Windows/SMB:MSFT_SmbConnection
CimInstanceProperties : {ContinuouslyAvailable, Credential, Dialect, Encrypted...}
CimSystemProperties   : Microsoft.Management.Infrastructure.CimSystemProperties

SmbInstance           : Default
ContinuouslyAvailable : False
Credential            : MicrosoftAccount\marticlilop@gmail.com
Dialect               : 3.1.1
Encrypted             : False
NumOpens              : 1
Redirected            : False
ServerName            : samba-server
ShareName             : WWW
Signed                : False
UserName              : DESKTOP-TDSK6R6\marti
PSComputerName        :
CimClass              : ROOT/Microsoft/Windows/SMB:MSFT_SmbConnection
CimInstanceProperties : {ContinuouslyAvailable, Credential, Dialect, Encrypted...}
CimSystemProperties   : Microsoft.Management.Infrastructure.CimSystemProperties



PS C:\Users\marti\scoop\apps\Gsudo\1.6.0>
```

**Comment by martinet101** [comment]
I can confirm that version 1.6 does not crash the computer, only versions 1.7.0 and 1.7.1 do

**Comment by martinet101** [comment]
1.4.1 crashes also. 

Version 1.4.0 only appears to work

**Comment by gerardog** [comment]
Does `gsudo -h` also crashes 1.4.1 ?

**Comment by gerardog** [comment]
Btw your server is using `Dialect: 3.1.1` which I understand means is using modern drivers... which shouldn't fail..

**Comment by martinet101** [comment]
> Does `gsudo -h` also crashes 1.4.1 ?

Yes



> Btw your server is using `Dialect: 3.1.1` which I understand means is using modern drivers... which shouldn't fail..

Yes, it is an up-to-date raspberry pi running smb4 (though W11 only supports smb3)

**Comment by gerardog** [comment]
I will create a few builds to find root cause. Just call the .EXE (command line parsing was disabled).

- 'debug/ShowVersionLite' => https://github.com/gerardog/gsudo/actions/runs/3168825686
This one is mostly Console.WriteLine. 

- 'debug/ShowVersion' => https://github.com/gerardog/gsudo/actions/runs/3168838863
Full ShowVersion without before and after. Mainly Assembly.GetExecutingAssembly();

Click the link, scroll down, download the artifact, test x64, please.

**Comment by martinet101** [comment]
First one: 
```
Microsoft Windows [Versión 10.0.22622.601]
(c) Microsoft Corporation. Todos los derechos reservados.

B:\Downloads>.\gsudo
Copyright(c) 2019-2022 Gerardo Grignoli and GitHub contributors
```

Second one:
```
B:\Downloads>.\gsudo cmd
gsudo v1.7.2-debug-ShowVersion.2 (Branch.debug-ShowVersion.Sha.f5c75b1abe6b4b67bef335fa750a422f962ad7a6)
Copyright(c) 2019-2022 Gerardo Grignoli and GitHub contributors
```

They both run fine now

**Comment by gerardog** [comment]
Hi, sorry for the delay, Can you test the following:

* debug/ShowHelp => https://github.com/gerardog/gsudo/actions/runs/3441304084

* latest CI build => https://github.com/gerardog/gsudo/actions/runs/3441035172
   But please test it as "gsudo -h" trying to make it fail at the help stage first.

If it works... Try `gsudo -h` in loop?
Or try to elevate with the latest CI build.

Also, did you reported this to Windows Feedback?

**Comment by gerardog** [comment]
Thanks for taking the time.
Then I guess the latest release (v2.0.2) should work too. Only difference is it is signed.

Not sure if the fact that the recent builds (including the latest v2.0.2 release) use the brand new .Net 7 release. (instead of the prerelease version) may have affected. Your machine may have received a windows update too... 

Should we wrap this issue and reopen if the problem reappears?

**Comment by martinet101** [comment]
Yes, for sure!
