### ISSUE TITLE
Issue: More than one instance of gsudo won't load in Windows Terminal when elevating as someone else.

### ISSUE THREAD

**Issue by mi271** [gerardog/gsudo#145]
I want to start an elevated CMD, Powershell or Powershell 7 Tab in Windows Terminal. First elevated Tab works fine, regardless if its cmd, Powershell or Powershell 7.
Second elevated tab throws timeout exception.

## Steps to Reproduce
 Created a profile within Windows Terminal
1.  gsudo cmd.exe
2. gsudo powershell.exe
3. gsudo pwsh.exe
4. 

## Screenshots
![image](https://user-images.githubusercontent.com/53559718/179010248-42472c4e-79f1-4340-b74c-afa867a7d41b.png)
![image](https://user-images.githubusercontent.com/53559718/179010385-47f78b42-64e6-47b4-80b5-510b877abc24.png)

## Context:
 - Windows version: Windows 10 21H2 Buidl 19044.1826
 - gsudo version:     1.3.0
[settings.txt](https://github.com/gerardog/gsudo/files/9112765/settings.txt)

**Comment by gerardog** [comment]
Ok. I see this happening only when invoking user is not admin, and you enter other user credentials.

This is what the debug window shows for the service.
![Screenshot 2022-07-14 233817](https://user-images.githubusercontent.com/3901474/179136192-691a7699-bd5c-4a0e-a35a-a22e9beed465.png)

To be honest I am not sure when I will have time to address this soon! I hope soon.

On the meantime I may suggest you open regular WT tabs, then write gsudo, and press enter, to elevate it in place. It should support many tabs, although showing many UAC popups.

**Comment by mi271** [comment]
Just for the info, it worked on my old laptop with gsudo 1.02 installed

**Comment by gerardog** [comment]
Gotcha. Fixed the issue (0d99418).

Nonetheless there is still a problem with the cache not working as desired on this scenario. 

To make the new process use the elevated uses environment vars (as requested in #113, (which should be relevant when elevating as someone else) it is using the attached mode. In this mode, the cache is locked until the current attached elevation ends. So opening simultaneous tabs will ask for credentials several times, but opening sequential tabs (closing the former first) will result in cache success. Nonetheless I think that one deserves a new ticket.

**Comment by gerardog** [comment]
Do you want to test the fix? 😉

https://ci.appveyor.com/project/gerardog/gsudo/builds/44183555/artifacts

**Comment by gerardog** [comment]
The cache should also be fixed, at the cost of starting another background gsudo service, on attached mode.

**Comment by mi271** [comment]
Will try it tomorrow when i get time. Friday is calling now

**Comment by mi271** [comment]
Thanks for the fix. Tried it today and it worked.
