### ISSUE TITLE
[Request]Provide a "uninstallSudo.ps1" script if gsudo was installed from latest "gsudoSetup.msi"

### ISSUE THREAD

**Issue by sebma** [gerardog/gsudo#149]
Hi,

Can you provide a "uninstallSudo.ps1" script if gsudo was installed from latest "gsudoSetup.msi" ?

**Comment by gerardog** [comment]
But, why?

Try `winget uninstall gerardog.gsudo`. Works even if installed from the `.msi`
Or go to add/remove programs, find gsudo, click uninstall.
Or find the original `.msi` file, right click, uninstall.

Anyway, here is your "uninstallSudo.ps1"

``` powershell
$id = (New-Object -ComObject WindowsInstaller.Installer).ProductsEx("","",7) | foreach { if ($_.InstallProperty("ProductName") -like "gsudo*") {$_.ProductCode()}}
if ($id) { & msiexec /x $id }
```

For v1.3.0, this will work too: `msiexec /x {4B7E1054-47CA-42CA-BDFE-5DA20B986819}`

**Comment by sebma** [comment]
@gerardog I don't have the `.msi` file anymore.

Thanks a lot for the other solutions :+1: , I'll try them tomorrow on my Windows environment.

Then, I'll use scoop to re-install it in $env:programdata/scoop :smile:.

Congratulations for this great tool :+1:
