### ISSUE TITLE
Issue: Cannot elevate powershell functions located in $PROFILE

### ISSUE THREAD

**Issue by KuraiAndras** [gerardog/gsudo#151]
## Steps to Reproduce
1. Create any function in your `$PROFILE`, for example:
```pwsh
function Run-Stuff {
 Write-Host "I ran"
}
```
2. Restart powershell to load the new profile
5. Call the function from powershell normally
6. Call the function with gsudo:
```powershell
gsudo Run-Stuff
```
Error:
```
Run-Stuff: The term 'Run-Stuff' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Error with debug:
```
Debug: Command Line: --debug Run-Stuff
Debug: Invoking Shell: PowerShellCore
Debug: Applying workaround for target app installed via MSStore.
Debug: Command to run: C:\Windows\system32\cmd.exe /s /c ""C:\Program Files\WindowsApps\Microsoft.PowerShell_7.2.6.0_x64__8wekyb3d8bbwe\pwsh.exe" -NoLogo -NoProfile -Command "Run-Stuff""
Debug: Using Console mode TokenSwitch
Debug: Caller PID: 20512
Debug: Caller SID: S-1-5-21-2633030068-227929540-914165460-1001
Debug: Elevating process: C:\tools\gsudo\v1.3.0\gsudo.exe --debug gsudoelevate 20512 S-1-5-21-2633030068-227929540-914165460-1001 All 00:00:00
Debug: Elevated instance started.
Debug: Connected via Named Pipe ProtectedPrefix\Administrators\gsudo_19C57EC9F97122414BC2E600B2E89CC57498D30D46B6B944187A3096DC5C847D.
Debug: CreateProcessAsUserWithFlags: C:\Windows\system32\cmd.exe /s /c ""C:\Program Files\WindowsApps\Microsoft.PowerShell_7.2.6.0_x64__8wekyb3d8bbwe\pwsh.exe" -NoLogo -NoProfile -Command "Run-Stuff""
Debug: ElevationRequest length 953
Debug: Process token successfully substituted.
Run-Stuff: The term 'Run-Stuff' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

## Screenshots

![image](https://user-images.githubusercontent.com/19240945/186090123-6a1baa7b-ab09-4f28-94bc-8705251dfd47.png)

## Context:
 - Windows version: 21H2 22000.856
 - gsudo version: v1.3.0 (Branch.master.Sha.24fb735f547e1e5dd7aa22fdd77777fa8c923a1c)

**Comment by gerardog** [comment]
Hi,
Please read this to see if it answers your question
https://gerardog.github.io/gsudo/docs/usage/powershell#profile-loading

**Comment by KuraiAndras** [comment]
Yes, thanks, I should have digged around the documentation

**Comment by gerardog** [comment]
No problem!
Excuse me if i sounded distant, I was walking fast and tried to help you as fast as possible.
Thanks for filling such a detailed issue. It certainly will show up on google search and help other find the right answer.

**Comment by KuraiAndras** [comment]
Thanks for the fast response and no, you did not sound distant. I ended up setting the environment variable, because placing `gsudo config PowerShellLoadProfile true` causes a message to be displayed when starting a new terminal session
```
PowerShellLoadProfile = "True" (user)
```

Now the start of my profile looks like:
```powershell
Import-Module 'C:\tools\gsudo\Current\gsudoModule.psd1'

$gsudoLoadProfile = $true
```

And so now everything works as expected. Thanks again.

**Comment by gerardog** [comment]
Setting a gsudo config value, like `gsudo config PowerShellLoadProfile true` will save it permanently in the registry. No need to execute more than once!
Glad to know you have it working!
