### ISSUE TITLE
gsudo frozen with cursor blinking and not returning prompt

### ISSUE THREAD

**Issue by servix** [gerardog/gsudo#155]
Hi! 
I was using gsudo 1.0.2 from a time ago....great tool...it always worked fine.
Today I've launched gsudo from a cmd and it stays there with the cursor blinking. Didn't return anything.
Waited for some minutes, tried to launch it from another console, nothing happens. No error received.
I've upgraded to 1.3.0, and tested, but the same happens. 

I've launched it with --debug and received this, but still hanged:

c:\>gsudo --debug
Debug: Command Line: --debug
Debug: Invoking Shell: Cmd
Debug: Command to run: C:\Windows\System32\cmd.exe /k
Debug: Using Console mode Attached
Debug: Caller PID: 18572

Current version:
c:\>gsudo -v
gsudo v1.3.0 (Branch.master.Sha.24fb735f547e1e5dd7aa22fdd77777fa8c923a1c)
Copyright(c) 2019-2021 Gerardo Grignoli and GitHub contributors

My OS: Windows 7 Pro SP1 x64 (Spanish)

Thanks!

**Comment by gerardog** [comment]
Hi,
Thanks for reporting. 

I´m guessing were the problem may be... Would you want to try this version?
https://ci.appveyor.com/project/gerardog/gsudo/builds/44593717/artifacts

Thanks.-

**Comment by servix** [comment]
Hola Gerardo, como estás? Recién veo que sos de mis pagos :-) 
Pero te respondo en inglés de todas formas para que quede registrada la respuesta por si a alguien más le sirve.

It worked fine with the version provided in the link. 
Thanks a lot
Best regards

**Comment by gerardog** [comment]
Excelente!

Will release the fix in the next version.

**Comment by servix** [comment]
Great, thanks so much.

Saludos!

**Comment by gerardog** [comment]
Follow me on twitter @gerardo_gr !
