### ISSUE TITLE
Issue: gsudo v1.3.1 detected as virus

### ISSUE THREAD

**Issue by dmagician038** [gerardog/gsudo#158]
## Steps to Reproduce
1.  Download ZIP/MSI
2. Unzip to a location given in PATH
---
## Screenshots
![image](https://user-images.githubusercontent.com/1897534/187458779-eea313de-652a-4287-9b27-1da3893c60e7.png)
---
## Version information:
 - Windows version: Windows 10 [Version 10.0.19044.1889] (x64)
 - gsudo version:      v1.3.1

**Comment by gerardog** [comment]
Thanks for letting me know.
We should report as false positive to ESET.

Just v1.3.1 is unsigned because the previous certificate expired. I have ordered a new code signing certificate with Sectigo, but it is still in process.

Next release definitely will be signed and hope wont show any false positives

**Comment by dmagician038** [comment]
Hi.

Not a bug but a-kind of issue:
Published by "github-actions[bot] <notifications@github.com>" (_as having 6 assets_):
```
Full Changelog: [v1.3.0...v1.4.0](https://github.com/gerardog/gsudo/compare/v1.3.0...v1.4.0)
—

This release has 6 assets:

    gsudo.v1.4.0.zip
    gsudo.v1.4.0.zip.sha256
    gsudoSetup.msi
    gsudoSetup.msi.sha256
    Source code (zip)
    Source code (tar.gz)
```
--
The actual [v1.4.0](https://github.com/gerardog/gsudo/releases/tag/v1.4.0) and [v1.4.1-build.100](https://github.com/gerardog/gsudo/releases/tag/v1.4.1-build.100) tags does not have the compiled binaries assets (MSI/Zipped EXEs)?

**Comment by gerardog** [comment]
Hi, yes...

I purchased a new code signing certificate days ago, from Sectigo. Unlike the previous, this one can be used to automate the release via GitHub Actions. I am working on that automation these days, so things are unstable. 

All artifacts must be created and signed correctly.  Also they need to be submitted as false positives to virus vendors incorrectly flagging it.

This takes some work. Unfortunatelly I may have created some tags for debugging, without realizing users would get a notification. Sorry for the spam!! Please be patient as the new release is coming out soon. 

To be honest, the next release v1.4.0 has same features as v1.3.0, but compiled with a different, faster, runtime. Same as v1.3.1 prerelease but properly signed. So it is safe to use v1.3 until I sort things out! 

Once the new pipeline and certificate is well oiled, new features will be faster to deliver. There is a lot of things in the backlog/issues. Please be patient! 😊

**Comment by dmagician038** [comment]
Hello.

First, thanks for your replay.

Second, I'm currently playing with your code and compiling it by myself (trying to understand all this new .net 6/7 multi platform, multi framework compilations), and your code looks like some kind of nice start point...

Thanks.

________________________________

**Comment by gerardog** [comment]
Glad to help. 

Use `Visual Studio 2022 preview` and .net framework 7 to have a 'normal' visual studio experience. Regular `Visual Studio 2022` will refuse to build net7.0.

Also, I am not an expert here. I am reading the docs, and moving forward one step at a time. It still feels weird when trying to choose which framework to debug.

**Comment by dmagician038** [comment]
Thank you for the info (I hope to put it for some good use 🙂🙏)

Thanks.

________________________________

**Comment by gerardog** [comment]
I've just released v1.4.0, and is clean on Virus Total. That includes ESET. 
I think we should thanks the code signing for the trust.

https://www.virustotal.com/gui/url/33b7607ee0696c665d66aad4a9a9ebefc6450fc0937221bc007423076501c075?nocache=1
https://www.virustotal.com/gui/url/befe3b9cd8f2ec60a8316128491ac18b57e35b49890460016de78e8ad2d61265?nocache=1

**Comment by dmagician038** [comment]
Great!

Have a good day!

Thanks.

________________________________

**Comment by gerardog** [comment]
The new certificate needs to build up some reputation in order to avoid being flagged as potentially unwanted app.

![image](https://user-images.githubusercontent.com/3901474/188655226-7d6e9503-2794-4590-bcfb-6f9fe5bcbd30.png)

I've submitted v1.4.1 to Microsoft Defender...

![image](https://user-images.githubusercontent.com/3901474/188655435-b45846e3-2395-451e-a2af-81d33b567ff9.png)

The warning still shows up on my system... We should wait a little bit more...
