### ISSUE TITLE
Issue: upgrading from WinGet restarts the machine automatically

### ISSUE THREAD

**Issue by felipecrs** [gerardog/gsudo#167]
## Issue Description

When I upgrade from 1.3.x to 1.4.0, and from 1.4.0 to 1.4.1, by using WinGet, it automatically restarted the computer. Ideally it shouldn't do that. If a restart is required, it should be signaled with an "Expected Return Code".

## Steps to Reproduce

1. Upgrade from 1.4.0 to 1.4.1 by using WinGet. 

## Context:
 - Windows version: Win11 Pro 22H2
 - gsudo version: 1.4.1

**Comment by gerardog** [comment]
You shall not upgrade using winget when gsudo is running!
Just kidding. Thanks for the bug report.

**Comment by felipecrs** [comment]
I understand... but what usually happens is that I run:

```console
gsudo winget upgrade --all
```

And I go grab a coffee. I don't know beforehand that `gsudo` itself would end up being upgraded as well.

**Comment by gerardog** [comment]
Yes. A winget issue, will need to investigate further.

https://github.com/microsoft/winget-cli/issues/229#issuecomment-911289529

**Comment by gerardog** [comment]
The manifest says it is a wix installer, and so it uses default winget arguments for wix. I can fix the manifests, but... Each release needs new manifests that are created by some bot, unknown to me.

**Comment by gerardog** [comment]
Its time to make the wix installer to allow upgrade even if file is use.

**Comment by felipecrs** [comment]
This is the bot: https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/src/winget-pkgs-automation/packages/g/gerardog.gsudo.json

And I think it will not automatically return back to WIX if you change the latest manifest to MSI.

**Comment by felipecrs** [comment]
> But,,, WIX detects gsudo.exe is in use and terminates it....
> So your winget upgrade --all will end badly...

I think that's okay, because as long as my computer does not reboot automatically I can check the error message and restart the installation without using GSudo if required.

**Comment by gerardog** [comment]
If you use gsudo to upgrade with `winget`:
![image](https://user-images.githubusercontent.com/3901474/188522467-ad4643af-de03-4315-951b-f0bb13c04094.png)

If gsudo is open, but you don't elevate winget, it fails like this...
![image](https://user-images.githubusercontent.com/3901474/188522396-cefbe2c7-0867-47ee-b551-d986912a9c11.png)

**Comment by felipecrs** [comment]
Awesome. I think the latter is only a very corner case.

**Comment by gerardog** [comment]
Oh dear... It never ends...

microsoft/winget-pkgs#78674
![image](https://user-images.githubusercontent.com/3901474/188524290-89477d99-c6fa-4a7a-a2d8-8b140c829f7f.png)

**Comment by felipecrs** [comment]
Yeah, this is very boring. I always give up fixing issues in batch because of this.

**Comment by gerardog** [comment]
Fixed!

**Comment by felipecrs** [comment]
Awesome, thank you so much Sir!
