### ISSUE TITLE
Issue: `Win32 internal error` over gsudo-elevated `Windows PowerShell` v5.1 

### ISSUE THREAD

**Issue by SiyuChen** [gerardog/gsudo#180]
![image](https://user-images.githubusercontent.com/22484673/192124579-a4d417bd-a74a-4254-8a5f-55b22c8f50cd.png)

**Comment by gerardog** [comment]
Hi,
I can't just guess everything, so please at least follow the bug issue template and context information to your issue:

- windows version
- gsudo version
- use gsudo --debug
- version of PSReadLine (do `Get-Module PSReadLine`)
- what scoop bucket are you pooling notepads-np from?
- does this problem repeats if you retry?

**Comment by SiyuChen** [comment]
Sorry about not following the bug issue template.

- windows version: Windows 21H1
- gsudo version: 1.6
- use gsudo --debug: 
![image](https://user-images.githubusercontent.com/22484673/192166097-5d081d39-a343-422a-af8f-e307f79ada28.png)
- version of PSReadLine: 2.0.0
- what scoop bucket are you pooling notepads-np from?  --- From one of official buckets of scoop, see https://github.com/ScoopInstaller/Nonportable/blob/master/bucket/notepads-np.json
- does this problem repeats if you retry? Yes, there is no issue when I install notepads-np with scoop, but the same error repeats every time when I uninstall notepads-np with scoop

**Comment by SiyuChen** [comment]
Also, if one uses double 'gsudo' to uninstall notepads-np, it seems to work,
![image](https://user-images.githubusercontent.com/22484673/192166408-c9f6cd13-f94a-4afa-b287-e682642d6952.png)

With a single gsudo, the Win32 internal error is always there.

**Comment by gerardog** [comment]
Thanks for the additional context. 

I've looked at that `notepads-np.json` [manifest](https://github.com/ScoopInstaller/Nonportable/blob/master/bucket/notepads-np.json), and it breaks at `Remove-AppxPackage`. It is its progress bar throwing error. 

I can also reproduce this on Win11, using Windows Powershell fails (not pwsh Core), by running: `gsudo "Write-Progress -Activity 'Title'"`.
![image](https://user-images.githubusercontent.com/3901474/192167760-8e4e2248-944f-484f-b3c3-3fa5575dd7de.png)

...but goes away when you wrap `powershell.exe` with some other app like `gsudo` (hence your double gsudo) or `cmd /c`
![image](https://user-images.githubusercontent.com/3901474/192167844-9b318808-625e-4981-969f-cdfcf71d14f3.png)

Workarounds:
- If you add this line to the manifest, the progress bar will not be shown and the uninstall will succeed:

``` powershell
$ProgressPreference = "SilentlyContinue"
```
- Use PowerShell v7 or newer.

**Help wanted:** Any Windows Internals, low-level guru willing to help me understand why `powershell.exe` with it's main process token replaced fails... but replacing the token of 'cmd /c powershell.exe' works.
