### ISSUE TITLE
Configurable Default User

### ISSUE THREAD

**Issue by samba2** [gerardog/gsudo#182]
## Description

For more convenience, particularly within scripts, it would be nice if I could specify a default user which is then already filled in when gsudo asks for the elevated privileges. 

Example:
```
gsudo -u myAdminUser
````

would present me with a credential dialog where *myAdminUser* is already filled in as the user.

**Comment by gerardog** [comment]
The user can't be prefilled on the Windows UAC popup. So at first sight, this is not doable.
But, this could be part of a bigger effort. I am slowly making up my mind about a design that could make this work.

Bottom line: this may take a while. But I take your feedback (and others, like #150) into consideration.
Please be patient...

**Comment by samba2** [comment]
All good. This is not urgent

**Comment by samba2** [comment]
Tnx @gerardog for working on this. Will try it out as soon as possible

**Comment by gerardog** [comment]
Hi @samba2! 
You are welcome. Several people requested this so eventually it was first on the list.
And sorry, I did not meant to close the issue yet. My intention was to keep it open until release, but GitHub closed it automatically when I merged the code. 
This will be available in the next release, which may be out today or tomorrow.

**Comment by gerardog** [comment]
Pre-Released: https://github.com/gerardog/gsudo/releases/tag/v2.0.0-preview
