### ISSUE TITLE
Issue: Cannot install office-365-apps-minimal with gsudo

### ISSUE THREAD

**Issue by SiyuChen** [gerardog/gsudo#185]
Not sure where is the origin of the problem. Some details have been given at https://github.com/ScoopInstaller/Nonportable/issues/65

![image](https://user-images.githubusercontent.com/22484673/193473170-f0c15dcd-198a-417a-a403-ba2eeae29af2.png)

The office-365-apps-minimal can be smoothly installed within a powershell that is run as administrator, but cannot be installed with a plain powershell + gsudo

I am using the lastest gsudo 1.7.1 and powershell 5.1

**Comment by gerardog** [comment]
Hi. I don't have access to a machine right now. Could you open powershell as administrator the old way (right click, run as admin), then run Scoop Install office....? If the same problem ocurrs without using gsudo, then we can discard gsudo being part of the problem

**Comment by SiyuChen** [comment]
> The office-365-apps-minimal can be smoothly installed within a powershell that is run as administrator, but cannot be installed with a plain powershell + gsudo

Yes, I have done the test.  The office-365-apps-minimal can be smoothly installed within a powershell that is run as administrator (i.e the old way). The problem only take place when I install office-365-apps-minima with a plain powershell + gsudo (i.e. gsudo scoop install office-365-apps-minimal-np)

**Comment by gerardog** [comment]
Ok. Can you please test:

gsudo cmd /c scoop install office-365-apps-minimal-np

**Comment by SiyuChen** [comment]
Thanks!! It works. Why is this?

**Comment by gerardog** [comment]
I'm speculating, maybe same issue as #180. powershell v5 has some issues with how gsudo replaces its token. I haven't figured out root cause, but wrapping in a caller process solves the problem.
Scoop has an internal powershell engine, so maybe related. #180 implements an 'gsudo config ExceptionList' to manage the process who fail, and scoop can be added there.

**Comment by gerardog** [comment]
gsudo v1.7.1 should have fixed this problem. On my test machine, it worked fine.
![image](https://user-images.githubusercontent.com/3901474/193480309-3c785cf6-8484-4982-9e8c-111da364569f.png)

See how `scoop install xx` turns into `cmd /c powershell -c scoop install xx`, which was what 1.7.1 was about:
![image](https://user-images.githubusercontent.com/3901474/193480443-1e0744fb-8848-41a0-861e-4a2a424cdff0.png)

My (working) scoop version.
![image](https://user-images.githubusercontent.com/3901474/193480326-3899be99-5ce2-4d2e-a7a9-6126ae1b2bc3.png)

Are you sure you are using gsudo 1.7.1? (try 'gsudo -v')

**Comment by SiyuChen** [comment]
Sorry, after checking everything, I found the problem actually originated from the app manifest. Scoop installed the app from afadlallah_scoopBucket by default (I thought it was installed from nonportable). afadlallah_scoopBucket is not under-maintained anymore so it has some bugs.

Sorry again for wasting your time. gsudo is really a fantastic tool!

**Comment by gerardog** [comment]
No problem
