### ISSUE TITLE
Issue: Script self elevation fails if the script location contains space for Powershell

### ISSUE THREAD

**Issue by TechnoSparks** [gerardog/gsudo#187]
## Issue Description

When using the script self-elevation code as [documented](https://gerardog.github.io/gsudo/docs/tips/script-self-elevation) in a PowerShell script, and if that script has a space or in a path where contains space, the script will fail and exits prematurely. It happens on both Windows PowerShell and Powershell 7 (pwsh)

## Steps to Reproduce

1.  Create a powershell script with a space in its name, eg `a script.ps1`
2. Use self-elevation boilerplate code as [documented](https://gerardog.github.io/gsudo/docs/tips/script-self-elevation)
3. Invoke the file `.\"a script.ps1"`

### Windows Powershell
![image](https://user-images.githubusercontent.com/6072210/194249455-6f54d3c0-4451-457b-a64a-3c568c095af5.png)
### pwsh 7
![image](https://user-images.githubusercontent.com/6072210/194249521-54ec22f1-382c-4048-8a3f-5d42c85d7487.png)

### if the script's path has no space
![image](https://user-images.githubusercontent.com/6072210/194250022-abf1c891-d289-42b2-a342-359980683a7d.png)

## Context:
  - Windows version: Win11 22H2 build 22623.730 
 
  - gsudo version:      v1.7.1

**Comment by TechnoSparks** [comment]
I tried calling the file manually based on the debug output:
```
Debug: Command to run: "C:\WINDOWS\system32\cmd.exe" /s /c ""C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -Command "C:\Users\TechnoSparks\Desktop\Windows Scripts\Iterate through Networks and set as Private.ps1""
```

Here is term output:
```powershell
PS C:\Users\TechnoSparks\Desktop\Windows Scripts> pwsh.exe -NoLogo -NoProfile -Command "C:\Users\TechnoSparks\Desktop\Windows Scripts\Iterate through Networks and set as Private.ps1"
C:\Users\TechnoSparks\Desktop\Windows: The term 'C:\Users\TechnoSparks\Desktop\Windows' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\TechnoSparks\Desktop\Windows Scripts>
```

It seems PowerShell cannot run it on its own either. But when I replace "-Command" to "-File" i can run the file successfully
```powershell
PS C:\Users\TechnoSparks\Desktop\Windows Scripts> pwsh.exe -NoLogo -NoProfile -File "C:\Users\TechnoSparks\Desktop\Windows Scripts\Iterate through Networks and set as Private.ps1"
WARNING: This script requires local admin privileges. Elevating...
Debug: Invoking Shell: PowerShellCore
Debug: Command to run: "C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -Command "C:\Users\TechnoSparks\Desktop\Windows Scripts\Iterate through Networks and set as Private.ps1"
Debug: Using Console mode TokenSwitch
Debug: Caller PID: 23132
Debug: Caller SID: S-1-5-21-1070348932-3240918504-2128446764-1012
Debug: Elevating process: C:\Program Files (x86)\gsudo\gsudo.exe --debug gsudoservice 23132 S-1-5-21-1070348932-3240918504-2128446764-1012 All 00:05:00
Debug: Elevated instance started.
Debug: Connected via Named Pipe ProtectedPrefix\Administrators\gsudo_241171989CC1B3E08A1729102608C6BCC0DD819C1CF02BE0A3FD53568AB9CB9E.
Debug: CreateProcessAsUserWithFlags: "C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -Command "C:\Users\TechnoSparks\Desktop\Windows Scripts\Iterate through Networks and set as Private.ps1"
Debug: Process token successfully substituted.
C:\Users\TechnoSparks\Desktop\Windows: The term 'C:\Users\TechnoSparks\Desktop\Windows' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Debug: Process exited with code 1
PS C:\Users\TechnoSparks\Desktop\Windows Scripts>
```

**Comment by TechnoSparks** [comment]
That solves it! Not a PowerShell expert, I am surprised that the ampersand is an answer for this!

**Comment by gerardog** [comment]
Yes, the ampersand means "execute this". Without it, it is "print this string". Glad to help. The docs has been updated.
