### ISSUE TITLE
Feature Request: Please use WinGet Releaser

### ISSUE THREAD

**Issue by ppvnf** [gerardog/gsudo#189]
GSudo is already available on Winget (gerardog.gsud) and it seems up to date, but would it be possible to use [WinGet Releaser](https://github.com/marketplace/actions/winget-releaser) to make future versions automatically available on Winget? 

(As of yet, Winget does not have the ability to carry out such automations natively: https://github.com/microsoft/winget-pkgs/issues/500)

Thanks to [vedantmgoyal2009](https://github.com/vedantmgoyal2009) efforts, GSudo now is automatically updated on Winget, but this isn't ideal because:

- Sometimes automation may go offline for maintenance, hence it is better to use GitHub Action. It is also easier to maintain and implement new features in the action. All apps use the latest manifest schema and fields.

- Automation is generally preferred for non-GitHub packages (meaning: software which are hosted on GitHub) that cannot take advantage of the GitHub Action.

- Since all GitHub API requests are authenticated with my account, using action distrubutes the amount of traffic on GitHub. The action is triggered automatically on releases, so we don't need to fetch APIs or scrape webpages to check for updates periodically, and PRs are created with the software's developer account.

- Microsoft prefers publishers managing releases for their apps themselves instead of a third party. It isn't a hard-and-fast rule, note the word "prefers" here.

**Comment by gerardog** [comment]
I would love to. I've asked my doubts on vedantmgoyal2009/winget-releaser#47

**Comment by gerardog** [comment]
It's working, Isn't it? https://github.com/microsoft/winget-pkgs/pull/86613

**Comment by ppvnf** [comment]
> It's working, Isn't it? [microsoft/winget-pkgs#86613](https://github.com/microsoft/winget-pkgs/pull/86613)

@vedantmgoyal2009

**Comment by vedantmgoyal2009** [comment]
Yes 🎉

**Comment by ppvnf** [comment]
Thank you both!
