### ISSUE TITLE
Issue: Using JPSoft TCC, for some reason trys to delete C:\*??

### ISSUE THREAD

**Issue by dmagician038** [gerardog/gsudo#201]
## Issue Description
While using JPSoft TCC28, when calling "gsudo -s --copyev" the app tries to execute "delete C:\\*"
The actual command is like ' _del / q_ "C:\WINDOWS\TEMP\gsudo\ed512b68-bd1c-449f-b312-e91f48f7512f.bat" '
**_Please note the extra spaces on ' **_ del /\<space\> q "C:\WINDOWS\TEMP\gsudo\\... ..." ' _**

## Steps to Reproduce
1.  TCC28 (no special options), 
2. Execute "gsudo -s --copyev"
3. during execution, Asking to delete "C:\*"

## Screenshots
During execution:
![image](https://user-images.githubusercontent.com/1897534/201034529-44ec2afa-0147-4f48-9ed9-02e411f8992a.png)

This one pops right after previous image (current user is local admin but the command is running as regular user not run as Administrator...)
![image](https://user-images.githubusercontent.com/1897534/201034724-bdbd722b-95d3-4eea-ac93-ba53523ebefc.png)

Together with this one
![image](https://user-images.githubusercontent.com/1897534/201034778-008564bc-3bfd-45c3-8b48-4d21f3c4df5e.png)

## Context:
  - Windows version: Windows 10, 22H2, 19045.2254
  - gsudo version:      v2.0.1

**Comment by gerardog** [comment]
There was a big typo here: https://github.com/gerardog/gsudo/blob/6d55e379195316e399f7be148a6a569f625feae5/src/gsudo/Helpers/CommandToRunAdapter.cs#L378

Fixed in v2.0.2
