### ISSUE TITLE
Issue: hangs and returns in pwsh without error message or action

### ISSUE THREAD

**Issue by meyerrn** [gerardog/gsudo#211]
## Issue Description

calling gsudo in a pwsh powershell (I tried 7.3.0 and 7.2.7) is using one core for some time and then returns without any action.
in "old" powershell and cmd its working fine.

## Steps to Reproduce

1.  start pwsh.exe
2. enter gsudo, or gsudo cmd
3. nothing happens. One cpu core fully used. After a while, command prompt reappears

## Context:
  - Windows version: Win11 21H2 
  - gsudo version: 2.0.3
(gsudo 2.0.2 is working fine)

**Comment by gerardog** [comment]
I've fixed the issue on v2.0.4. Please update.

Nonetheless, you seem to have installed gsudo as a dotnet global tool. That is not supported by gsudo, see [this note](https://gerardog.github.io/gsudo/docs/usage/powershell):

> If you installed `PowerShell Core` as a `dotnet global tool` [you will have issues](https://github.com/PowerShell/PowerShell/issues/11747). 
>
> You can check by running `dotnet tool list --global`. If so, uninstall and use any another installation method such as: `winget install Microsoft.PowerShell` / `choco install pwsh` / [Download from GitHub](https://github.com/PowerShell/PowerShell/releases/latest) / [Microsoft Store](https://apps.microsoft.com/store/detail/powershell/9MZ1SNWT0N5D)
