### ISSUE TITLE
Error: `Unable to connect to the elevated service.` on `Windows 7`

### ISSUE THREAD

**Issue by servix** [gerardog/gsudo#215]
Hola Gerardo, como estas?

I'd like to report a new issue, it seems it was present on issues #40 and #42, but I've upgraded today and it's present on the latest release.
Previously I was running this version: https://ci.appveyor.com/project/gerardog/gsudo/builds/44593717/artifacts because at that moment the current
version didn't worked because of issue #155

Current version: 
`gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)`

Debug info:
```
Debug: Invoking Shell: Cmd
Debug: Command Line: --debug
Debug: Command to run: C:\Windows\system32\cmd.exe /k
Debug: Using Console mode TokenSwitch
Debug: Caller PID: 12068
Debug: Caller SID: S-1-5-21-1564449222-2518250070-4161321324-1000
Debug: Elevating process: C:\Program Files (x86)\gsudo\gsudo.exe --debug gsudoelevate 12068 S-1-5-21-1564449222-2518250070-4161321324-1000 All 00:00:00
Debug: Service process started.
Error: Unable to connect to the elevated service.

```

When I ran it with --debug, it opens a new window with this information:
```
Caller Pid: 7064
Running as:
User: ----- \ ---
Sid: S-1-5-21-1564449222-25182SøøVø-4161321324-1øø1
Is Admin: True
Integrity Level: High (12288)
Credentials Cache :
Mode: Explicit
Available for this process: False
Total active cache sessions: 0

Processes attached to the current console:
PID
12648
PPID Integrity 
7064 High
UserName
---- \ ----
Name
C:\Program files (x86)\gsudo\gsudo .exe (this gsudo status)

Info: Service started
Debug: Service will shutdown if idle For
Debug: Listening on named pipe ProtectedPrefix\Administrators\gsudo_C1EA31F17684 '9E5B6098765FD31981703F4B8B147E011EB4637BCF013E98129.
Debug: Access allowed only For Process ID 12068 and children
Debug: NamedPipeServer listening.
Info: Service stopped
Service shutdown. This window will close in 15 seconds 

```

My OS: Windows 7 Pro SP1 x64 (Spanish)

Thanks,
Saludos!!!
Guillermo

**Comment by gerardog** [comment]
Hi, I am investigating the issue.
In the meantime, you can use v1.4.0 that works for sure on W7

**Comment by gerardog** [comment]
Fixed!
Bonus track: the Credentials Cache that never worked on W7 is fixed!

Try this
https://github.com/gerardog/gsudo/releases/tag/v2.0.5-ChocoInstallPreview

**Comment by servix** [comment]
Thank you very much!
Fixed and working fine now.

Best regards
