### ISSUE TITLE
Feature Request: Windows ARM64 native execution support

### ISSUE THREAD

**Issue by awakecoding** [gerardog/gsudo#217]
## Description

Build and package gsudo to ensure that it runs as a native Windows ARM64 application without x86 or x64 emulation. I've installed it on Windows 11 for ARM on a Windows Dev Kit (Project Volterra), and here's what happens:

- gsudo.exe is installed in "C:\Program Files (x86)\gsudo", rather than "C:\Program Files\gsudo"
- gsudo.exe launches in x64 emulation mode, instead of native ARM64 execution mode.

## Proposed technical details

Build a proper Windows ARM64 gsudo package, as a separate MSI installer or zip file, and ensure it is installed under "C:\Program Files" with the correct target architecture. MSI installers normally contain only one target architecture, so I'd recommend producing separate MSI installers, one for each target platform (x86, x64, arm64).

Once launched, the Windows task manager should show "ARM64" as the architecture for the gsudo process, instead of "x64":
![image](https://user-images.githubusercontent.com/295841/204326087-6a32f905-960c-4623-94d6-1066cc53d664.png)

**Comment by gerardog** [comment]
Hi @awakecoding,

Yes, i agree, I even:
- was tweeting about it a few days back https://twitter.com/gerardo_gr/status/1590153188300460032 . (You can see how new I am to arm64)
- had some in progress work #191 (PR #214)

You should be able to fetch a signed Arm64 build from the artifacts [here](https://github.com/gerardog/gsudo/actions/runs/3566909691) (scroll down, Binaries link). 

Regarding:

> MSI installers normally contain only one target architecture

Yes, It's a limitation not on WIX but on Windows Installer... 
I ended up doing [this trick](https://stackoverflow.com/a/15573689/97471) for x86/x64, but has this side effect of installing to `Program Files(x86)`. I personally don't like having different packages per platform...

> ... so I'd recommend producing separate MSI installers, one for each target platform (x86, x64, arm64).

Yeah... It looks like that is where everyone is going... 

The installer may take a while, but please test the Arm64 build !

**Comment by awakecoding** [comment]
@gerardog it sounds like the timing is good! I've downloaded this recent ARM64 CI build and installed it manually under "C:\Program Files\gsudo", and it works like a charm, thanks!

![image](https://user-images.githubusercontent.com/295841/204353333-79cbbd0f-f07b-4c71-87c5-4a12642730ae.png)

The next step would be proper packaging, but I confirm that the executable runs in native ARM64 execution mode

**Comment by gerardog** [comment]
Great.

Did you pick the binaries from the `CI Build` pipeline or `Release`? Only the latter are code-signed.
Anyway, I just enabled NativeAOT in the [latest build](https://github.com/gerardog/gsudo/actions/runs/3567713647) which should be slightly faster.

**Comment by awakecoding** [comment]
I don't recall which one I picked, but it works. It's fine if it wasn't the most optimized build available ;)

**Comment by BMurri** [comment]
I believe the package part of this was done in release v2.0.6 via #243.
