### ISSUE TITLE
Issue: Please don't use --help instead for Get-Help

### ISSUE THREAD

**Issue by bckelley** [gerardog/gsudo#220]
## Steps to Reproduce

1.  Get-Help sudo (Get-Help gsudo) produces respectively
![image](https://user-images.githubusercontent.com/15696431/207934871-d0cda578-7719-4569-a3b6-f6de95142066.png)
![image](https://user-images.githubusercontent.com/15696431/207934923-b075ea72-7bd3-4aeb-842c-b970f54077d5.png)
returns garbage
2. Run gsudo (sudo) --help returns
![image](https://user-images.githubusercontent.com/15696431/207935420-9d40a144-ee00-4bfd-b3b6-d80d4eb7f8fe.png)
for both

## Context:
  - Windows version:

gsudo version 2.0.4
winver 22H2 19045.2364

**Comment by mattcargile** [comment]
Not sure what you are after. Do you want the native `get-help` to return what `gsudo --help` returns or the vice versa? I'm of the impression that this is how all native commands work in respect to "help". If you wanted `help gsudo` to return `gsudo --help`, one would need to write a wrapper/proxy" function. This would be for all native commands inside `pwsh`.

**Comment by gerardog** [comment]
Hi @bckelley, you may want to update to the latest gsudo, then add `Import-Module gsudoModule`, and the you can do Get-Help gsudo to get a rich help text.
