### ISSUE TITLE
Feature Request: sudo !! (sudo bang bang)

### ISSUE THREAD

**Issue by gerardog** [gerardog/gsudo#23]
To be fair, this is not my top priority but a nice-to-have. Upvote if you would like to see this feature implemented sooner.

from: https://stackoverflow.com/a/15137462/97471

> The bang bang (`!!`) command is a shortcut to **repeat the previous command you entered in your terminal**. This command is very useful when you forget that you need admin rights to make a certain action, and lets you repeat it with super-user rights just by typing
> 
>     sudo !!
> 
> instead of typing arrow-up, scrolling to the beginning of the line, adding `sudo ` and hitting enter (imagine scrolling through those *loooong* `apt-get` commands). So many seconds gained! *Yay!*
> 
> [![sudo bang bang][1]](http://blog.alestanis.com/2013/02/27/the-bang-bang-command/)
> 
> There are many other bang-commands such as `!x`, `!?x`, `!!:p` and `!!*`. This [blog post][2] lists them and explains what they are for.
> 

  [1]: http://i.stack.imgur.com/qwsbJ.png
  [2]: http://craig-russell.co.uk/2011/09/28/bang-bang-command-recall-in-linux.html

**Comment by gerardog** [comment]
Check it out on [v0.7.1](https://github.com/gerardog/gsudo/releases/tag/v0.7.1)

**Comment by bearbattle** [comment]
Hi there! I encounter an issue with this feature:

![Bang Bang Fails](https://user-images.githubusercontent.com/48974238/162210366-af8ee885-bd66-4966-8def-b0f85a84a1c7.png)

**Comment by bearbattle** [comment]
After import this to my `$PROFILE`, this feature not work for me either.

![Module Imported](https://user-images.githubusercontent.com/48974238/162356643-b4e74c5c-1f4b-4691-a654-6bc97d9698da.png)

**Comment by gerardog** [comment]
Sorry if the documentation is not very clear.
The feature is for: gsudo !!
To make it work as sudo !!, Add to the bottom of your profile:

# Create an custom alias:
Set-Alias 'sudo' 'gsudo'

And please restart your consoles

**Comment by bearbattle** [comment]
Thanks!
