### ISSUE TITLE
Issue: Portable gsudo.exe now deliberately flagged as PUP `Generic.Application.Gsudo` by BitDefender

### ISSUE THREAD

**Issue by Xeevis** [gerardog/gsudo#232]
## Issue Description
It appears BitDefender has now took a hardline against gsudo and this time not as false positive, but in a deliberate attempt as it identifies threat as `Generic.Application.Gsudo`. It will rigorously block any attempt to download the portable version with Antivirus, Advanced Threat Defense and Online Threat Prevention as all flag the `gsudo.exe` and will block download or will quarantine aby archives or installers that bundle it (as is the case with WingetUI).

This doesn't affect the MSI installer in any way and using the installed gsudo.exe by 3rd party processes is fine as well.

## Screenshots 
1. Can't download the ZIP file
![image](https://user-images.githubusercontent.com/5835044/216936865-b1b8d475-39f7-4faf-b180-89ad0a912347.png)

2. Can't install when bundled in another installer
![wingetUI_bitdefender](https://user-images.githubusercontent.com/5835044/216942261-c1ee1593-1af3-4a82-8e3c-d830475e3e65.jpg)

3. Scanner will quarantine any stragglers bundling it
![image](https://user-images.githubusercontent.com/5835044/216942095-00c74024-f3a2-4f67-a533-b5500d0f1189.png)

4. gsudo installed with MSI installer is left alone and when WingetUI is set to use installed gsudo no suspicious behavior is detected either
![image](https://user-images.githubusercontent.com/5835044/216941851-fe4be48a-e4eb-4f52-abd8-35e2c409ee39.png)

5. VirusTotal
![image](https://user-images.githubusercontent.com/5835044/216959416-c49b519c-65f0-4311-8976-c18e0ab81a71.png)

## Context:
  - Windows version: Win11 22H2
  - gsudo version: 2.0.4 (affects at least 10 most recent versions)
  - BitDefender Total Security | Build 26.0.32.123

**Comment by gerardog** [comment]
What can I do?

This is game over for the project.

**Comment by gerardog** [comment]
It seems to only affect the .Net46/AnyCpu build.

**Comment by ppvnf** [comment]
Info about how to contact av vendors https://www.techsupportalert.com/how-to-report-malware-or-false-positives-to-multiple-antivirus-vendors/

**Comment by gerardog** [comment]
Seems to be fixed
https://www.virustotal.com/gui/file/36f707d9bc63a7e4fd953a35119bbe2fd32f3c2440bc7ccecc9a64c981d83ece
![image](https://user-images.githubusercontent.com/3901474/232548268-91d54375-51e7-47fb-8273-5f07bf452a08.png)

https://www.virustotal.com/gui/file/41b771d80e220764875be4adb47341589b6b8259560e38dc4059aad5ed2e0228
