### ISSUE TITLE
Feature Request: Extend `gsudo status` with additional flags

### ISSUE THREAD

**Issue by martin-rueegg** [gerardog/gsudo#236]
## Description

In order to avoid unnecessary UAC prompts, it would be helpful to have a way to get some information about the available caches/PIDs, E.g. it might be useful to display a message before the UAC prompt, explaining that the UAC will appear and why that is the case (I know, this is just informational, and certainly cannot be trusted from a security point of view).

But you might also want to give the user the option, whether or not to do a certain operation, based on whether or not cached credentials are available (e.g. you want to turn on the cache ahead of time, in order to avoid delays due to user input during time critical actions).

In my particular case, the test to find out whether or not I will need elevated privileges during the time-critical actions has in itself a side-effect, that would start the time-critical window. As such, I now need to ask for elevated permission, even if I later find out I would not have required them. Also, then deleting the cache is not an option, unless I know that I was instantiating the cache, and that it has not already been instantiated. However, `gsudo cache on` returns no different output or return code depending on whether the UAC had to be prompted.

All this information can be retrieved from the output of `gsudo status`. However, [parsing it can be quite cumbersome](https://github.com/gerardog/gsudo/blob/446183930b71d1ea61fa2d19b286befc07aa4a49/docs/docs/tips/script-self-elevation.md#self-elevate-script).

### Documentation

```
Status arguments:
  is-cached | cached       # Shows if the current caller PID has cached credentials. 
  is-elevated | elevated   # Shows if the current caller PID is running in elevated mode.
  is-admin | admin         # Check if is Admin
  can-level | can | level  # Check if a given integrity level can be assumed (without raising UAC prompt)
  timeout                  # Shows the current set timout.
  help                     # Shows this documentation (equivalent to `-h` or `--help` options).

Status options
 -p | --pid  {pid}         # Query information about the given PID, rather than the current caller PID.
 -s | --seconds            # Return timeout information in seconds, rather than MM:SS to Standard Output.
                           # (Only valid for `timeout` argument.)
 -h | --help               # Shows this documentation (equivalent to `help` argument).
```

<br/>

### `status is-cached`

<dl>
  <dt><strong>Description</strong></dt>
    <dd>Returns information about available credentials.</dd>
  <dt><strong>Correspondence to <samp>gsudo status</samp></strong></dt>
    <dd><samp>Available for this process</samp></dd>
  <dt><strong>Syntax</strong></dt>
    <dd><pre>gsudo status <strong>is-cached</strong> [ --pid {pid} ]</pre></dd>
  <dt><strong>Alias</strong></dt>
    <dd><pre>gsudo status <strong>cached</strong></pre></dd>
  <dt><strong>Return code/Errorlevel</strong></dt>
    <dd><code>0</code>: Cache is available<br/>
        <code>1</code>: Cache is not available</dd>
</dl>

<br/>

### `status is-admin`

<dl>
  <dt><strong>Description</strong></dt>
    <dd>Returns whether a process is administrtor (i.e. integrity level is High or System).</dd>
  <dt><strong>Correspondence to <samp>gsudo status</samp></strong></dt>
    <dd><samp>Running as: Is Admin</samp></dd>
  <dt><strong>Syntax</strong></dt>
    <dd><pre>gsudo status <strong>is-admin</strong> [ --pid {pid} ]</pre></dd>
  <dt><strong>Alias</strong></dt>
    <dd><pre>gsudo status <strong>admin</strong></pre></dd>
  <dt><strong>Return code/Errorlevel</strong></dt>
    <dd><code>0</code>: Is Admin<br/>
        <code>0</code>: Is no Admin</dd>
  <dt><strong>Standard Output</strong></dt>
    <dd><code>True</code><br/>
        <code>False</code></dd>
</dl>

<br/>

### `status is-elevated`

<dl>
  <dt><strong>Description</strong></dt>
    <dd>Returns information about elevation level.</dd>
  <dt><strong>Correspondence to <samp>gsudo status</samp></strong></dt>
    <dd><samp>Running as: Integrity Level</samp></dd>
  <dt><strong>Syntax</strong></dt>
    <dd><pre>gsudo status <strong>is-elevated</strong> [ --pid {pid} ]</pre></dd>
  <dt><strong>Alias</strong></dt>
    <dd><pre>gsudo status <strong>elevated</strong></pre></dd>
  <dt><strong>Return code/Errorlevel</strong></dt>
    <dd><code>??</code>: Untrusted<br/>
	    <code>4096</code>: Low<br/>
	    <code>8192</code>: Medium<br/>
	    <code>8448</code>: MediumPlus<br/>
	    <code>12288</code>: High<br/>
	    <code>16384</code>: System<br/></dd>
  <dt><strong>Standard Output</strong></dt>
    <dd><code>Untrusted</code><br/>
        <code>Low</code><br/>
        <code>Medium</code><br/>
        <code>MediumPlus</code><br/>
        <code>High</code><br/>
        <code>System</code></dd>
</dl>

<br/>

### `status can-level`

<dl>
  <dt><strong>Description</strong></dt>
    <dd>Checks whether or not a certain integrity level can be assumed.</dd>
  <dt><strong>Correspondence to <samp>gsudo status</samp></strong></dt>
    <dd>N/A</dd>
  <dt><strong>Syntax</strong></dt>
    <dd><pre>gsudo status <strong>can-level</strong> [ {level} ] [ --pid {pid} ]</pre></dd>
 <dt><strong>Alias</strong></dt>
    <dd><pre>gsudo status <strong>can</strong></pre>
        <pre>gsudo status <strong>level</strong></pre></dd>
  <dt><strong>Possible input values <code>level</code></strong></dt>
    <dd><code>Admin</code>: Can at least assume High integrity level.<br/>
        <code>Untrusted</code><br/>
        <code>Low</code> | <code>4096</code><br/>
        <code>Medium</code> | <code>8192</code><br/>
        <code>MediumPlus</code> | <code>8448</code><br/>
        <code>High</code> | <code>4096</code><br/>
        <code>System</code> | <code>12288</code><br/>
        <code>Installer</code></dd>
  <dt><strong>Default <code>level</code></strong></dt>
    <dd><code>Admin</code>: Can at least assume High integrity level.</dd>
   <dt><strong>Return code/Errorlevel</strong></dt>
    <dd><code>0</code>: Can assume requested level<br/>
        <code>1</code>: Cannot assume requested level</dd>
  <dt><strong>Standard Output</strong></dt>
    <dd><code>True</code><br/>
        <code>False</code></dd>
</dl>

<br/>

### `status cache-timeout`

<dl>
  <dt><strong>Description</strong></dt>
    <dd>Returns the set timeout.</dd>
  <dt><strong>Correspondence to <samp>gsudo status</samp></strong></dt>
    <dd>N/A</dd>
  <dt><strong>Syntax</strong></dt>
    <dd><pre>gsudo status <strong>cache-timeout</strong> [ --seconds ] [ --pid {pid} ]</pre></dd>
  <dt><strong>Alias</strong></dt>
    <dd><pre>gsudo status <strong>timeout</strong></pre></dd>
  <dt><strong>Return code/Errorlevel</strong></dt>
    <dd><code>-1</code>: until logoff or <code>cache off</code>, or <code>-k</code><br/>
	    <code>{seconds}</code>: Seconds of timout</dd>
  <dt><strong>Standard Output</strong></dt>
    <dd><code>-1</code> For no timeout (until logoff or <code>cache off</code>, or <code>-k</code>)<br/>
        <code>{hh:mm:ss}</code> Hours, minutes and seconds, as given to the <code>--duration</code> option.<br/>
        <code>{ss}</code> Seconds, if <code>--seconds</code> option  given.</dd>
</dl>

**Comment by martin-rueegg** [comment]
Happy to help with documentation and testing.

**Comment by gerardog** [comment]
Hi, 
 
>  In order to avoid unnecessary UAC prompts, it would be helpful to have a way to get some information about the available caches/PIDs, 

Yes,. that one was the intention behind gsudo status.

> E.g. it might be useful to display a message before the UAC prompt, explaining that the UAC will appear and why that is the case (I know, this is just informational, and certainly cannot be trusted from a security point of view).

What are the possible reasons you may think of? I can only think of one, user requested elevation and no cache is available.

> But you might also want to give the user the option, whether or not to do a certain operation, based on whether or not cached credentials are available (e.g. you want to turn on the cache ahead of time, in order to avoid delays due to user input during time critical actions).

Like `gsudo --fail-if-no-cache-available SomeCommand`? That sounds doable.

> In my particular case, the test to find out whether or not I will need elevated privileges during the time-critical actions has in itself a side-effect, that would start the time-critical window. As such, I now need to ask for elevated permission, even if I later find out I would not have required them.

Not sure I am following you here. If you use `gsudo status` then the `Available for this process: True` should indicate that you can elevate without a UAC. Then you can do `gsudo cache on --duration HH:MM:SS` to restart the timeout period and set it to what you want.

> Also, then deleting the cache is not an option, unless I know that I was instantiating the cache, and that it has not already been instantiated. However, gsudo cache on returns no different output or return code depending on whether the UAC had to be prompted.

> All this information can be retrieved from the output of gsudo status. However, [parsing it can be quite cumbersome](https://github.com/gerardog/gsudo/blob/446183930b71d1ea61fa2d19b286befc07aa4a49/docs/docs/tips/script-self-elevation.md#self-elevate-script).

Yeah, it's not nice. I agree... 

This is one way to find if we are elevated, from CMD:

`gsudo status | findstr /C:"Is Admin: True" >NUL && Echo I am Admin`

Or to find if we can elevate without a UAC prompt:

`gsudo status | findstr /C:"Available for this process: True" >NUL && Echo I can elevate silently`

Maybe save the result in a variable for future use:
```
set CacheAvailable=0
gsudo status | findstr /C:"Available for this process: True" >NUL && Set CacheAvailable=1
if %CacheAvailable%==1 call gsudo cache on --duration 10:00
```

There may be room to have a way to fetch each variable separately. Will look at each case later when I found more time.

**Comment by martin-rueegg** [comment]
Hola Gerardo

Thanks for getting back to me and the time you took to look into this and the examples you have given.

Yes, I'm aware of the possibility to parse the output of `gsudo status`. In fact, I so far have implemented it this way. Nonetheless thank you for the examples you have given. Much appreciated.

But point was about avoiding to grep/parse the output of the current `gsudo status`. I thought an API that it less prone to errors (change of output format, additional output information, change of codepage, etc.) would be useful.


> There may be room to have a way to fetch each variable separately. Will look at each case later when I found more time.

If you'd have time to look into this at some point would be amazing.

The following are only responses to your reply. No need to read any further unless you're working on an implementation. Happy the be of any help, if I can.

Thanks,
Martin.


----

> > E.g. it might be useful to display a message before the UAC prompt, explaining that the UAC will appear and why that is the case (I know, this is just informational, and certainly cannot be trusted from a security point of view).
> 
> What are the possible reasons you may think of? I can only think of one, user requested elevation and no cache is available.

For example, in a login script in a corporate network you want to check if a certain tool is available or otherwise install it. For the installation process elevation is required. Now the user is used that the login script runs through silently. But you as admin have installed a new tool. Now you might want to check if that tool is available and, if not, inform the user that it's going to be installed and therefore a UAC of "gsudo" will be shown. (I know you could do that with Group Policy and stuff. But sometimes the poor man's way is what is much simpler to deploy in a smaller network.)

----

> > But you might also want to give the user the option, whether or not to do a certain operation, based on whether or not cached credentials are available (e.g. you want to turn on the cache ahead of time, in order to avoid delays due to user input during time critical actions).
> 
> Like `gsudo --fail-if-no-cache-available SomeCommand`? That sounds doable.

Yes, that might be an option. It would not work for the login script scenario - as you can be sure to not have elevation when the user logs in unless you have asked for UAC already once during the login procedure... 

But I'd prefer querying the availability of the cache specifically and then act based on that information to avoid conflict of the return codes or output messages (did it come from gsudo not being able to issue the command, or from the command itself?).

With my suggested command line arguments this could be achieved quite easily with \
`gsudo status is-cached && gsudo SomeCommand`

Hence not much effort to achieve your suggested solution. But beyond that you would have at the same time the opportunity to do something like

``` batch
if gsudo status is-cached (
  echo Some message
  SomeCommand
  echo Some other message
) else (
 echo I'm sorry Dave, I'm afraid I can't do that!
)
```

Of course this could also be done with your solution, but that is _very_ ugly:

``` batch
if gsudo --fail-if-no-cache-available True (
   ...
)
```

**Comment by gerardog** [comment]
Hey, sorry it really took me long to get to it... You know, I do this on my spare time... So, here is my attempt:

![image](https://github.com/gerardog/gsudo/assets/3901474/b738d540-ced0-4212-8504-6be0669eb526)

**Comment by martin-rueegg** [comment]
Hi @gerardog 

Thank you so much for your effort. I appreciate you spending your spare time for such a project and I know that there is also a life aside coding ...!

Yes, your solution looks great! Thank you so much.

Form your screenshot it is not clear - as there is no cache session active - if the timeout of such a session can be retrieved.

As far as I understand, the suggestion I made at the outset of this issue have been implemented as follows:

- `is-cached` => `gsudo status CacheAvailable`
- `is-elevated` => `gsudo status IsElevated`
- `is-admin` => `gsudo status IsAdminMember`
- `can-level` not directly implemented, but can be checked if `gsudo status IntegrityLevelNumeric` is greater or equal to the level one is looking for? However, in a DOS Command Prompt/Batch this requires an extra step by storing the return value into avariable first and then compare it. Being able to supply the requested level e.g. as in `gsudo status canIntegrityLevel [level]` would allow to just test the return code.
- `timeout` => maybe possible to retrieve from the CacheSessions array ...

Would it be possible to index the `ConsoleProcesses` array with the PID? This would it make easier to just retrieve the information about a given process. Even more simple it would be if the optional parameter `--pid` would be supported for the status properties `isElevated` (is in the list of `ConsoleProcesses`), `IntegrityLevel`/`IntegrityLevelNumeric`, `UserName`, `Executable`.

Also, I would suggest to rename the `Integrity` property of the `ConsoleProcesses` into `IntegrityLevel` for  consistency and also add `IntegrityLevelNumeric`.

Anyway, thank you so much for your improvments! Awesome.

**Comment by gerardog** [comment]
> Form your screenshot it is not clear - as there is no cache session active - if the timeout of such a session can be retrieved.

No, it's not. A cache session is not an open elevated service accepting queries from any process. It really sound like you are using gsudo in ways is not meant to be used.

Microsoft wont change Cmd.exe anymore because it would break it's backwards compatibility. In other words, `.BAT` and `.CMD` are deprecated. Almost everything in `.cmd` is a hack, like:

![image](https://github.com/gerardog/gsudo/assets/3901474/fcc53c11-7fac-4993-a5ce-25a159307610)

On powershell it would just be `if ((gsudo status CacheAvailable) -eq "true") { gsudo dir }`.
![image](https://github.com/gerardog/gsudo/assets/3901474/9e2b837f-994f-419c-912d-662a9c0d7c8e)

To retrieve the configured timeout use `gsudo config CacheDuration`. 
```
$> gsudo config CacheDuration
CacheDuration = "00:05:00"
```

> Would it be possible to index the ConsoleProcesses array with the PID? This would it make easier to just retrieve the information about a given process. Even more simple it would be if the optional parameter --pid would be supported for the status properties isElevated (is in the list of ConsoleProcesses), IntegrityLevel/IntegrityLevelNumeric, UserName, Executable. 

The reason being you dont want to parse it? I think you should use the right tool, which in this case is PowerShell. 

```
PS C:\> powershell -noprofile -c '(gsudo status --json | ConvertFrom-Json).ConsoleProcesses[0]'
Pid        : 46884
Ppid       : 5084
Integrity  : Medium
UserName   : DESKTOP\gerar
Executable : C:\Program Files\WindowsApps\Microsoft.PowerShell_7.3.1.0_x64__8wekyb3d8bbwe\pwsh.exe

PS C:\> powershell -noprofile -c '(gsudo status --json | ConvertFrom-Json).ConsoleProcesses[0].Executable'
C:\Program Files\WindowsApps\Microsoft.PowerShell_7.3.1.0_x64__8wekyb3d8bbwe\pwsh.exe
```

Regarding `can-level`: If your process is elevated or cache is available, `can-level` is true for any level. If both are false, `can-level` is false for any integrity higher than current. It can't be done for other processes.

**Comment by martin-rueegg** [comment]
I've made a suggestion in #280 on how my request could be implemented.

So far, I did not implement the `--can-level` flag.
