### ISSUE TITLE
Feature Request: Split MSI installer into three platforms -- the easy way

### ISSUE THREAD

**Issue by BMurri** [gerardog/gsudo#243]
## Description
Glancing through your issues list, it appears that you are already thinking about separate installers for each platform, which is actually how Windows Installer is designed to be used. As an expert with Windows Installer and having been a contributor to the WiX toolset for almost 20 years, I would like to help you implement that for this utility that looks quite compelling.

## Proposed technical details
It has always been possible to create separate platform MSIs reusing the same WiX sources (and project) but it wasn't all that easy in WiX v3, especially with its connection to the Framework versions of MSBuild. I propose helping you convert your current installer project to WiX v4 (which is `dotnet` tool friendly) and make it multi-platform ready all in one swoop and integrate it into your current release scripts. BTW, WiX v4 is already production ready and will likely be released in less than 4 months.

If you'd like my help, assign this issue to me and I'll start a series of pull requests to get the ball rolling.

**Comment by BMurri** [comment]
I will create my PR against `Feature.PlatformMSI`.

Each MSI package's filename will be suffixed with the platform identifier prefixed with a dash, so `gsudoSetup-x86.msi`, `gsudoSetup-x64.msi`, & `gsudoSetup-arm64.msi`. I'll let you deal with how that affects your publish pipelines to nuget, winget, & chocolatey (beyond the obvious reference to the current filename [here](https://github.com/gerardog/gsudo/blob/72221239e61d84a2551dc6a9d8143f4ff3abe938/.github/workflows/release.yml#L62), where I'll change it to `gsudoSetup-*.msi`).

Expect a first PR this week.

**Comment by gerardog** [comment]
Released in v2.0.6

**Comment by gerardog** [comment]
Thank you @BMurri for the implementation!
