### ISSUE TITLE
Issue: Upgrade didn't update path to gsudoModule.psd1 in the PowerShell profile file.

### ISSUE THREAD

**Issue by trparky** [gerardog/gsudo#246]
## Issue Description
I launched a Terminal instance and it gave me an error.

## Steps to Reproduce
1. Launch Terminal.
2. Look at error.

## Screenshots 
![image](https://user-images.githubusercontent.com/32105035/227744466-d3ad8e87-fa3c-4b3f-846c-7e4137db41e4.png)

## Context:
 Windows version: Windows 11 22H2 (22621.1413)
gsudo version: gsudo v2.0.6 (Branch.tags-v2.0.6.Sha.6da4723971cc95f4285797b31545ddfdd2ceca0d)

The issue was fixed by manually updating the "Microsoft.Powershell_profile.ps1" file in the $env:HOMEPATH\Documents to read
Import-Module 'C:\Program Files\gsudo\Current\gsudoModule.psd1'
Instead of
Import-Module 'C:\Program Files (x86)\gsudo\gsudoModule.psd1'

**Comment by royvou** [comment]
See last release notes!

BREAKING CHANGE: If you added gsudo module to your Powershell profile update its path to %ProgramFiles%\gsudo\Current or even better just do Import-Module (Get-Command gsudoModule.psd1).Path and let it pick up from your PATH variable.

**Comment by gerardog** [comment]
It's hard to improve things without breaking any existing flow. This PowerShell module is especially delicate as each user may or not have imported the module on pwsh.

This release changes the install path (something users were asking for a while) but does not change the binaries much. Should I have upgraded the major version for this reason? Maybe yes. Sorry about that. Not sure if your upgrading process distinguishes between major or minor updates or, in other words, if pushing to versioning as v3.0.0 would have made any difference for you.

What do you suggest? the installer to get into the local powershell profiles and update gsudo's module path?

**Comment by BMurri** [comment]
When installers that install system-wide reach into individual user profiles, it never ends well (unless everyone commits to never creating any more than one user profile per machine ;) ). This issue will only afflict pain one-time per user that either didn't check the release notes or didn't realize that those notes affected them, and the fix workaround is as simple as @royvou suggests.

**Comment by omaru-ok** [comment]
`sudo !! ` isn't workign for me too  
![image](https://user-images.githubusercontent.com/108952834/230773383-78053da2-d9c6-4d5b-b5be-e546aa8f43c5.png)

this is $profile
![image](https://user-images.githubusercontent.com/108952834/230773397-2d72a794-6dde-4bc0-8a46-747fe773c3bd.png)

:( what is wrong? 
```
> sudo -v
gsudo v2.0.6 (Branch.tags-v2.0.6.Sha.6da4723971cc95f4285797b31545ddfdd2ceca0d)
Copyright(c) 2019-2022 Gerardo Grignoli and GitHub contributors
```
```
pwsh -v
PowerShell 7.3.3
```

**Comment by gerardog** [comment]
> :( what is wrong?

The module is loading fine, and redefines `gsudo` but not `sudo`. That needs to be manually done: add `Set-Alias 'sudo' 'gsudo'` to your module

**Comment by omaru-ok** [comment]
> Set-Alias 'sudo' 'gsudo'

worked fine but `sudo !!` do not persist the nvim config anymore :(
before sudo !! : the normal way 
![image](https://user-images.githubusercontent.com/108952834/230828699-6c665349-4f6d-4f6a-9862-035241842492.png)


after sudo !! : it do not load nvim config
![image](https://user-images.githubusercontent.com/108952834/230828746-6f57f199-c14a-4e12-882a-8d833e899d85.png)

**Comment by gerardog** [comment]
I'll close this issue, because there is no solution that fits all scenarios. I trust the user to be able to keep the profile file updated. Sorry that the breaking change broke your flow.

**Comment by gerardog** [comment]
@omaru-ok : `sudo !!` and `gsudo !!` are well intentioned hacks, but they definitely have a lot of problems that could never be fixed. Please retry your scenario using gsudo, but not `!!`, and if you still need help please fill a new issue. Thank you.
