### ISSUE TITLE
Issue: Running vim using sudo hangs.

### ISSUE THREAD

**Issue by sebthom** [gerardog/gsudo#248]
## Issue Description
I am trying to run vim with sudo but the process hangs.

## Steps to Reproduce
1.  Install [scoop](https://scoop.sh/)
2.  Install **gsudo** and **git-with-openssh** via scoop
3. Try to execute vim via sudo, e.g.
    ```
    > C:\scoop\shims\sudo.exe C:\scoop\shims\apps\git-with-openssh\current\usr\bin\vim.exe
    ```
    This results in a blank command window that does not react to any keyboard interaction. Aborting using CTRL+C is ignored.

The same works fine using this sudo implementation: https://github.com/chrisant996/sudo-windows/

## Screenshots 

![image](https://user-images.githubusercontent.com/426959/230609219-d3add335-bfc2-4ce9-89db-5004b71be453.png)

## Context:
  - Windows version:  Microsoft Windows [Version 10.0.19045.2728]  22H2 - English
  - gsudo version: gsudo v2.0.6 (Branch.tags-v2.0.6.Sha.6da4723971cc95f4285797b31545ddfdd2ceca0d)

**Comment by sebthom** [comment]
Seems to work when I use the **-copyev** flag for some reason.

**Comment by gerardog** [comment]
If I `gsudo vim` and then kill `vim.exe` it will show the arrow keys as a character escape sequence, which is something I havent seen before, maybe this is a problem handling the console mode.
![image](https://user-images.githubusercontent.com/3901474/230717189-454c5142-e933-4c10-839b-847912ab90bf.png)

I'll investigate, but in the meantime you can workaround it by running:

`gsudo config ExceptionList = "notepad.exe;powershell.exe;vim.exe;"` 

...that will wrap `vim` into `cmd /c vim`. That avoids the problem. 

> Seems to work when I use the --copyev flag for some reason.

Yes `gsudo --copyev vim` does `cmd /c RunBatchFileWithEnvVars & vim`, so the savior `CMD` is added.
