### ISSUE TITLE
Issue: No # admin promt suffix on Powershell

### ISSUE THREAD

**Issue by MrMarvel** [gerardog/gsudo#252]
## Issue Description
No indication of admin rights on Powershell.
On cmd.exe it works perfectly*

## Intended version
In powershell after elevating suffix changes:
USER>  =>  USER#

## Steps to Reproduce

1.  Install gsudo via winget
2. Open powershell
3. run gsudo

## Screenshots
![image](https://user-images.githubusercontent.com/24212110/231877436-87f9b67c-3edc-434d-abed-547c08f4d2a5.png)
![image](https://user-images.githubusercontent.com/24212110/231878482-a1530c94-09a3-41f9-9753-577544aa96e4.png)

## Context:
  - Windows version:  Win10 Pro 22H2 -> 
  - gsudo version:  v2.0.6 (Branch.tags-v2.0.6.Sha.6da4723971cc95f4285797b31545ddfdd2ceca0d)

**Comment by Pome-ro** [comment]
So this is something you can do via a PowerShell Prompt customization. If you set a custom profile, you can change your prompt based on if you're in admin or not. 

In PowerShell you can edit your profile by typing `code $profile` (if you have vscode installed, any editor will do). Then add this to the profile ps1 file. 

```powershell
function prompt {
	$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
	$testAdmin = $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
	$promptSymbol = ">"
	If ( $testAdmin ) {
		$promptSymbol = "#"
	}
	Write-Host "PS $((location).path)$promptSymbol"
}
```
This gets your current security principal and then checks if it is in the Administrator role. The `Write-Host` line is what appears before your cursor in PowerShell. So you could technically write anything there, and it will appear before your cursor. You could do something like this as well, for example:

```powershell
function prompt {
	$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
	$testAdmin = $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
	$promptStatus = "USER"
	$promptColor = "White"
	If ( $testAdmin ) {
		$promptStatus = "ADMIN"
		$promptColor = "Red"
	}
	Write-Host "[$promptStatus] " -ForegroundColor $promptColor -NoNewLine
	Write-Host "PS $((location).path)>"
}
```
This will result in a prompt that looks like the two examples below:

* If not admin: `[USER] PS C:\>` with white text for [USER]
* If admin: `[ADMIN] PS C:\>` with red text for [ADMIN]

You can read more about prompt customization from Microsoft's help page: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_prompts?view=powershell-7.3

If you want to get really fancy with it, you can also look into https://ohmyposh.dev/

**Comment by gerardog** [comment]
Perfectly explained, thank you @Pome-ro
