### ISSUE TITLE
Issue: Can't elevate execution of a PS1 script

### ISSUE THREAD

**Issue by trparky** [gerardog/gsudo#267]
## Issue Description
I'm trying to elevate the execution of a PS1 script.

## Steps to Reproduce
1. Execute... sudo & '.\Backup VMs Batch File.ps1'.
2. It doesn't work.

## Screenshots 
![image](https://github.com/gerardog/gsudo/assets/32105035/84c5841a-cf7c-47c6-b4e9-ded0c7294d1d)

## Context:
  - Windows version: 22H2 (OS Build 22621.1778)
  - gsudo version: gsudo v2.0.9 (Branch.tags-v2.0.9.Sha.0a8889d483c3224321ba48acec5e3b9fe87c62f3)

**Comment by 237dmitry** [comment]
I use:

```powershell
Invoke-Gsudo -ScriptBlock { script }

# or with path to script

Invoke-Gsudo -ScriptBlock { some\path\to\script.ps1 }
```

```powershell
Get-Command -Module gsudomodule
```

**Comment by gerardog** [comment]
Hi @trparky, I see your problem. Take a look at the [docs](https://github.com/gerardog/gsudo#usage-from-powershell--powershell-core) where it is explained how to use gsudo on pwsh.
I would use `gsudo { scriptblock }`, as is the shorter syntax to use gsudo on powershell. `Invoke-gsudo` also works, it is slower in some scenarios but being a proper `pwsh` function adds `tab` auto complete and parameter bindings that helps (with `gsudo module`).  
In both cases, you need the curly braces `{}`, so `pwsh` does not interpret your `&` as the [background job operator](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.3#background-operator-), and lets gsudo receive and elevate the complete command.
