### ISSUE TITLE
Issue: UAC keeps popping up 

### ISSUE THREAD

**Issue by suntong** [gerardog/gsudo#274]
## Issue Description

UAC keeps popping up under Git Bash.

## Steps to Reproduce

Under Git Bash that I installed freshly today.

1. sudo echo abc
2. sudo echo abc
3. gsudo echo abc
4. gsudo echo abc

Each time UAC would pops up.

## Context:
  - Windows version:

![image](https://github.com/gerardog/gsudo/assets/422244/97e3d531-f30c-4f7e-8272-68eb6c7f5cac)

```
$ gsudo -v
gsudo v2.1.0 (Branch.tags-v2.1.0.Sha.530d77b2c8a545592aa089e76428f81ec1f0151a)
```

**Comment by gerardog** [comment]
Please enable gsudo cache by running 'gsudo config CacheMode auto'.

**Comment by suntong** [comment]
BINGO! Thanks!!
