### ISSUE TITLE
Issue: Installer should drop module to %ProgramFiles%\WindowsPowerShell\Modules, not %ProgramFiles%\PowerShell\Modules

### ISSUE THREAD

**Issue by dartraiden** [gerardog/gsudo#277]
Without this, the `Import-Module gsudoModule` command cannot locate the module.

**Comment by gerardog** [comment]
Still using Windows Powershell ? Fair enough, I'll change the location since seems to work fine on both versions (5.x & 7.x)

**Comment by gerardog** [comment]
Released in v2.3.0
