### ISSUE TITLE
Can it support SSH/non-GUI logins?

### ISSUE THREAD

**Issue by fatso83** [gerardog/gsudo#28]
AFAIK, `gsudo` relies on the UAC graphical prompt. Is this a limitation of Windows or is there a way of working around this? 

My shop has a few windows boxes and we would like to automate some procedures using ssh that we currently need to login via RDP to do. Today we need to Right-Click and run Powershell as Admin, but it would be great if we could just do `ssh user@mybox elevate "C:/scripts/do-admin-stuff.ps1"`

**Comment by gerardog** [comment]
gsudo is an interactive tool, same as Unix/Linux sudo. Currently lacks any 'sudoers' functionality as in "always allow user A to execute Command1 as user B, without prompting for consent". I am hesitant to add a UAC Bypass mode because I don't want antiviruses to flag it as a malicious.

I would recommend you to create a Scheduled Task, (check the ["Run with highest privileges"](https://www.digitalcitizen.life/use-task-scheduler-launch-programs-without-uac-prompts) option) 
That would give you a way to execute a script with elevation, even schedule it, or trigger start remotely (with powershell without ssh). 

Then: `ssh user@mybox "C:/scripts/Start-Scheduled-Task1.ps1"`

**Comment by fatso83** [comment]
OK, thanks. That would not work for us, unfortunately, as it's an interactive control script.

**Comment by gerardog** [comment]
- Shouldn't the SSH server provide a way to open an elevated session? (what ssh server is it?)
- How about disabling UAC on that box?

If nothing else is available... There is a hack that you could use.. launching the gsudo elevated instance using the task scheduler.... that would bypass the UAC to launch the elevated gsudo service,  then you could use gsudo from the command line to elevate, without the interactive popup... not a supported scenario right now, but it could work... probably not with the latest release. Let me know if you want to test it out...

**Comment by fatso83** [comment]
It's just the normal [Win32 OpenSSH server](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_overview)

Does not seem to be fixed
- https://github.com/microsoft/vscode-remote-release/issues/1430
- https://github.com/PowerShell/Win32-OpenSSH/issues/962

**Comment by gerardog** [comment]
Have you fixed this?

As I've made progress into v0.7, there is a way that may help you on this scenario.
This is a UAC ByPass, so it's not 'oficially' supported.

You will need to manually install the latest build: (unzip and add to the path, removing previous versions)
https://ci.appveyor.com/project/gerardog/gsudo/builds/31889267/artifacts

Then do a remote desktop session, and run this as administrator:
```
powershell -c "$Sta = New-ScheduledTaskAction -Execute 'C:\git\gsudo\src\gsudo\bin\gsudo.exe' -Argument 'cache on -p 0' ; $Stset= New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries ; Register-ScheduledTask GsudoCache -Action $Sta -RunLevel Highest"
```
It creates a task that starts the credentials cache (`gsudo cache on`) (new feature in v0.7, not yet documented in the home) but using the elevation provided by the task scheduler.

Then on SSH run this:
````
:: Start the cache
SCHTASKS /Run /TN "GsudoCache"

:: wait a few seconds for the cache to start
TIMEOUT 3

:: run the elevated command 
gsudo MyAppConsoleApp
```
Hope it helps.

**Comment by fatso83** [comment]
@gerardog I am not sure how I missed this, but I think the Win32 Open SSH server is actually running my process with the highest privilege already 🙈 . I think I was confused by trying to run an interactive command from the default `cmd` login and it just not doing anything. `.controll-script.ps1 <Enter>` and then just ... nothing. 

After I executed `powershell` in the session the interactive command above worked and I could do everything I am used to doing with a UAC elevated powershell session. Sorry for wasting your time.

**Comment by gerardog** [comment]
LOL!, glad you solved it.

Don't worry, I was already working on v0.7 release. It just happened to have the explicit 'cache on' feature that could work on your scenario. I was looking to investigate this either way.
