### ISSUE TITLE
Issue: Unhandled Exception when using gsudo on Powershell 7.3.6

### ISSUE THREAD

**Issue by cartifanwlr** [gerardog/gsudo#282]
## Issue Description
Running gsudo (or with the sudo alias) will return an Unhandled Exception on Powershell 7.3.6. This issue does not happen on Command Prompt or Windows Powershell.

## Steps to Reproduce

1. Open Powershell (pwsh) 
2. Elevate a command with gsudo
3. Observe the bug.

## Screenshots 

![image](https://github.com/gerardog/gsudo/assets/109605173/a99a0a66-23d7-405e-8c14-b67b134eb167)
![image](https://github.com/gerardog/gsudo/assets/109605173/97b202a4-930c-4fb8-8717-4fbe0bdeffcf)

## Context:
  - Windows version: Windows 11 version 23H2 (Beta Channel) build 22631.2115

**Comment by cartifanwlr** [comment]
This issue is indeed caused by the Microsoft Store version of Powershell. I reinstalled with Winget and gsudo now works fine.

**Comment by gerardog** [comment]
That's great! Can you please let me know if you were able to reproduce the error elevating without gsudo? Thank you

**Comment by cartifanwlr** [comment]
> That's great! Can you please let me know if you were able to reproduce the error elevating without gsudo? Or you just installed using winget before trying that? Thank you

Elevating without gsudo did indeed work.
