### ISSUE TITLE
Issue: scoop global install reports failure

### ISSUE THREAD

**Issue by yonizaf** [gerardog/gsudo#283]
## Issue Description

installing gsudo globally via scoop (i.e `scoop install -g gsudo`) reports failure, the program installs but scoop reports failure, and no version number is shown.

The same problem affects updating via scoop as well. (see https://github.com/ScoopInstaller/Main/issues/4989)

## Steps to Reproduce

1.  run `scoop install -g gsudo` in any elevated command shell.
2. ...profit!

## Screenshots 

![image](https://github.com/gerardog/gsudo/assets/598326/828f706e-e10f-43f3-a989-b1ca97de775c)
![image](https://github.com/gerardog/gsudo/assets/598326/8ebd6d77-1a24-45ce-a249-fa0c57e23c1c)

## Context:
  - Windows version: 11 22H2 
 
  - gsudo version:      2.3.0

**Comment by gerardog** [comment]
This is a scoop issue. To be honest I didn't know about `scoop install -g`.

I've created https://github.com/ScoopInstaller/Scoop/issues/5601 so they can address this issue.

**Comment by gerardog** [comment]
I've created a PR for Scoop: ScoopInstaller/Scoop#5611

**Comment by gerardog** [comment]
The PR has been merged! Solved
