### ISSUE TITLE
Feature Request: Unelevate Console

### ISSUE THREAD

**Issue by shawnwildermuth** [gerardog/gsudo#284]
## Description
This might be impossible, but I wanted to opine about unelevating a console that you've elevated (with gsudo by itself). I know I can call gsudo with the command I want, but sometimes I need to be elevated for a series of work and don't want to re-execute the shell.

## Proposed technical details
I would propose:

```bash
c:\>gsudo

# so some work in elevated console

c:\>gsudo --leave
```

Feel free to close if it isn't possible.

**Comment by gerardog** [comment]
When you call `gsudo` (without a specifying a command) a new elevated shell (`cmd.exe` in this case) is started.
You can type `exit` on the elevated shell to close it, and return to the original (non-elevated) cmd.
(similar as how it would work in unix/linux sudo)

Please close if this answer solves your problem!

**Comment by shawnwildermuth** [comment]
That was it. Forest through the trees and all that. Thanks!

**Comment by gerardog** [comment]
And btw, if you are elevated you can start a non-elevated process too using 'gsudo -i medium' (for medium integrity level)
