### ISSUE TITLE
Feature Request: Add '#' to lines in elevated shell process? (to mimic Linux)

### ISSUE THREAD

**Issue by e-t-l** [gerardog/gsudo#316]
## Description

I have no idea if this is even possible, but could an octothorpe symbol `#` be prepended each line in the elevated shell process created by gsudo? In addition to being a nice aesthetic similarity to the Linux shell, its presence would also be a visible reminder to the user that they are working in an elevated process.

## Proposed technical details

Just like how a sudo-elevated Linux shell line starts with `username@hostname:~/directory:#`, gsudo in Windows CMD would look like
`C:\Users\Username\directory>#

Ideally, the octothorpe would be nonfunctional (i.e. the shell/interpreter completely ignores it) and not able to be deleted or removed without exiting the elevated process.

All things considered, I recognize this is probably a low-priority enhancement, and a potentially difficult one to execute. Just wanted to run the idea by you!

**Comment by gerardog** [comment]
In Windows CMD it is already doing it:
![image](https://github.com/gerardog/gsudo/assets/3901474/e43e6fc4-1190-469c-8c37-947af9ceb319)

In Powershell you need to run: `notepad $profile` and add the following lines:

```
Import-Module "gsudoModule"
Set-Alias prompt gsudoPrompt
```
and that will enable the behaviour:
![image](https://github.com/gerardog/gsudo/assets/3901474/77392dae-a6f5-4609-b14a-430fec7c066e)

**Comment by e-t-l** [comment]
Ah, so it does. I think I got this repo confused with https://github.com/janhebnes/chocolatey-packages/blob/master/Sudo/Readme.md. Sorry to waste your time!
