### ISSUE TITLE
Issue: Wrong SID when using cached token

### ISSUE THREAD

**Issue by Starmania** [gerardog/gsudo#321]
## Issue Description

When you cached a token (e.g. the one of system) and you gsudo an another time, arguments like --ti, -u, `none` won't be respected and you still run as system.

## Steps to Reproduce

```bash
gsudo config CacheMode Auto
gsudo "cmd /c whoami"
gsudo -s "cmd /c whoami"
```

## Screenshots 

![image](https://github.com/gerardog/gsudo/assets/52313983/edf64208-4781-4016-bc9f-11c76c6aff90)

## Potential place to look at
- https://github.com/gerardog/gsudo/blob/49446f9ee4f8f4d7f8794781b1b1b0f14f245cd2/src/gsudo/Commands/RunCommand.cs#L116-L121

## Context:
  - Windows version:
    - Win10 21H2 - French 
  - gsudo version:      
  	- v2.4.0 (5cb99680b71a0116c002c5b42d9d6ac249786914)

**Comment by gerardog** [comment]
I've released a fix in v2.4.2. Please give it a try. Thank you for reporting.
