### ISSUE TITLE
Commands with Bool ($True/$False) Paramiters do not run within a gsudo session

### ISSUE THREAD

**Issue by hossimo** [gerardog/gsudo#349]
## Issue Description

I get different results from an elevated Powershell vs a Normal one, this seems to happen when I use a Command that requires a $True or $False parameter.

## Steps to Reproduce
1.  From within a non-elevated powershell  I run the command `gsudo Disable-NetAdapter -Name "Ethernet" -Confirm:$False`
2. This gives the the following error after UAC:
> Disable-NetAdapter : Cannot convert 'System.String' to the type 'System.Management.Automation.SwitchParameter'
> required by parameter 'Confirm'.
> At line:1 char:44
> Disable-NetAdapter -Name Ethernet -Confirm:False -Verbose
>                                            ~~~~~
>     CategoryInfo          : InvalidArgument: (:) [Disable-NetAdapter], ParameterBindingException
>     FullyQualifiedErrorId : CannotConvertArgument,Disable-NetAdapter
> 

However, if I run the same command from an elevated (obviously without (g)sudo) PowerShell it works correctly:

It almost looks like the gsudo is converting the $False to a string "False"

## Screenshots

Working from Elevated:
![image](https://github.com/gerardog/gsudo/assets/1986602/fe0d251a-12e7-44d9-9f16-f201081cf1ce)

Not working from Normal PS:
![image](https://github.com/gerardog/gsudo/assets/1986602/227e45af-ab94-4fa4-aaf6-608257c1e4e3)

## Context:
  - Windows version: Win11 23H2 (Build 22631.3447)
  - gsudo version:      gsudo v2.4.4 (Branch.tags-v2.4.4.Sha.cf887bf98d5d3d90fc1eebc08c7a277afb50cd19)

**Comment by gerardog** [comment]
Please enclose your command to elevate in single quotes, or even better: in `{}` brackets

You will find this information usefull:
https://gerardog.github.io/gsudo/docs/usage/powershell#using-gsudo-scriptblock-syntax

**Comment by hossimo** [comment]
Thanks so much for answering, Typical RTFM for me :)

Thanks again this has been a real help! now I just need to make an alias for `!!`

**Comment by gerardog** [comment]
Lol, happy to help :)

And btw, don`t make an alias for `!!`, write `gsudo`, press space, and then press tab, for example:

``` powershell
PS C:\> echo something
something
PS C:\> sudo [press tab key]
PS C:\> sudo { echo something }      # magic autocomplete
```
(this requires `Import-Module gsudoModule` in your [profile](https://gerardog.github.io/gsudo/docs/usage/powershell#gsudo-powershell-module) )

**Comment by hossimo** [comment]
Amazing! Thanks so much again! I'm so glad this will be in Windows by default. I bounce between Windows, Mac and Debian constantly and this is a huge help for my mental gymnastics.

**Comment by gerardog** [comment]
Microsoft's sudo is like 2019's gsudo. You may still want to run `winget install gsudo` ;)
