### ISSUE TITLE
crashpad error

### ISSUE THREAD

**Issue by elig0n** [gerardog/gsudo#35]
running gsudo 0.7.0 installed via chocolatey under Windows 10 shows the following error:

	[41808:53392:20200525,083449.588:ERROR crash_report_database_win.cc:569] 
	CreateDirectory : The system cannot find the path specified. (3)
	Could not initialize crash reporting DB
	Can not init crashpad with status: CRASHPAD_DB_INIT_ERROR

Also reported on crashpad's bugtracker : https://bugs.chromium.org/p/crashpad/issues/detail?id=343

**Comment by gerardog** [comment]
Hi,
How do I get a build of crashpad? 
I checked the nightly builds but they don't seem to produce artifacts.

**Comment by elig0n** [comment]
I'm not sure. I assumed gsudo interfaces with it somehow. So it's not related to gsudo then ?

**Comment by gerardog** [comment]
What were you tying to do? Which steps lead you to the error?

**Comment by elig0n** [comment]
I just ran gsudo in cmd

**Comment by gerardog** [comment]
Could you please run `gsudo --debug` and paste the output?
Also, please try to figure out how why `gsudo` is launching `crashpad` on your system, given `crashpad` is not part of gsudo

**Comment by gerardog** [comment]
Closing this, as I wasn't able to reproduce it.
There is a small chance that this is fixed with #32.

**Comment by elig0n** [comment]
Eventually I removed and reinstall and it went away.
