### ISSUE TITLE
Incorrect quoted string parsing

### ISSUE THREAD

**Issue by jaidTw** [gerardog/gsudo#38]
The space character within the quotes seems to be tranformed into a newline character.
Using ver 0.7.0 installed from chocolatey

```
➜  ~ echo "ABC DEF"
ABC DEF
➜  ~ sudo echo "ABC DEF"
ABC
DEF
```

**Comment by gerardog** [comment]
`gsudo` is a console app, not a cmdlet, so PowerShell has it's ways to handle character escaping that I can't change.
You will see the same issues if you call PowerShell from PowerShell. Try:
```
❯ powershell -c 'echo "abc def"'
abc
def
❯ powershell -c echo "abc def"
abc
def
```

To call `gsudo` from PowerShell, you need to follow the quoting rules defined in the [home](https://github.com/gerardog/gsudo#usage-from-powershell--powershell-core).

> You can pass a string literal with the command that needs to be elevated. [PowerShell Quoting Rules](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules) apply. 
> Note that `gsudo` returns a string that can be captured, not powershell objects.
> 
> `PS C:\> gsudo 'powershell string command'`
> 
> **Examples:**
> 
> ``` PowerShell
> 
> # Commands without () or quotes  
> PS C:\> gsudo Remove-Item ProtectedFile.txt
> or
> PS C:\> gsudo 'Remove-Item ProtectedFile.txt'
> 
> # On strings enclosed in single quotation marks ('), escape " with \"
> $hash = gsudo '(Get-FileHash \"C:\My Secret.txt\").Hash'
> # For variable substitutions, use double-quoted strings with single-quotation marks inside
> $hash = gsudo "(Get-FileHash '$file' -Algorithm $algorithm).Hash"
> # or escape " with \""
> $hash = gsudo "(Get-FileHash \""$file\"" -Algorithm $algorithm).Hash"
> ```

So, if you follow the guidelines and replace double quotes " with \\"" (backslash d-quote d-quote)

```
❯ gsudo 'echo \""abc def\""'
abc def

❯ powershell -c 'echo \""abc def\""'
abc def
```

This could be improved by introducing an `invoke-gsudo' cmdlet, with better object marshalling and handle parsing at a different level, but I still have not endeavour into this.

**Comment by jaidTw** [comment]
I didn't notice that is a PowerShell problem, thanks for your explanation!

**Comment by gerardog** [comment]
You are welcome! Hopefully with #39 the escaping rules can be improved.
