### ISSUE TITLE
Unable to connect to the elevated service

### ISSUE THREAD

**Issue by fiasko** [gerardog/gsudo#42]
On my laptop the gsudo fails every time I use it either in Windows Terminal or in Powershell. I'm using Windows 1909 currently. On my desktop computer with Windows 10 2004 it works fine. Here's the error messages I get with --debug option.

`Debug: IsWindowsApp(""C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"") = False ("C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe")
Debug: Command to run: "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo
Debug: Using Console mode TokenSwitch
Debug: Caller PID: 3664
Debug: Caller SID: S-1-5-21-2868004287-1937137488-1281371712-1002
Debug: Elevating process: C:\ProgramData\chocolatey\lib\gsudo\bin\gsudo.exe --debug gsudoservice 3664 S-1-5-21-2868004287-1937137488-1281371712-1002 All 00:05:00
Debug: Elevated instance started.
Error: Unable to connect to the elevated service.`

and gsudo service error:
`Info: Service started
Debug: Service will shutdown if idle for 00:05:00
Error: System.Security.Principal.IdentityNotMappedException: Joidenkin tai kaikkien tunnisteviittauksien muuntaminen epäonnistui.
   kohteessa System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   kohteessa System.Security.Principal.NTAccount.Translate(Type targetType)
   kohteessa System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   kohteessa System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(AccessRule rule)
   kohteessa gsudo.Rpc.NamedPipeServer.<Listen>d__16.MoveNext()
--- Pinon jäljityksen loppu aiemmasta sijainnista, jossa palautettiin poikkeus ---
   kohteessa System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   kohteessa System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   kohteessa gsudo.Commands.ServiceCommand.<Execute>d__19.MoveNext()
--- Pinon jäljityksen loppu aiemmasta sijainnista, jossa palautettiin poikkeus ---
   kohteessa System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   kohteessa System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   kohteessa gsudo.Program.<Start>d__1.MoveNext()`

Sorry for the Finnish localization. I can translate them if needed.

**Comment by gerardog** [comment]
The fix was released in [v0.7.1](https://github.com/gerardog/gsudo/releases/tag/v0.7.1).
Thanks for reporting the problem.
