### ISSUE TITLE
!! for PowerShell?

### ISSUE THREAD

**Issue by Christoph-Wagner** [gerardog/gsudo#44]
The just released 0.7.1 doesn’t support `!!` for PS. At face value, this seems like it should be pretty straight forward using Get-History, but I don’t have much experience with PS and even less with using PS from C#. I would like to look into it, but was wondering if you tried and encountered any showstoppers' or problems that might make this moot or extremely complicated.

**Comment by gerardog** [comment]
It's not a trivial task.
Currently gsudo is just the `gsudo.exe` C# app. `gsudo !!` on CMD uses a Windows Console API's to get its parent CMD history. On PS, there is no global WinApi call, and the c# App can't access the invoked PS session. Calling `Get-History` on another PS process ('pwsh -c Get-History') will return a empty or different list. 
Maybe connecting to the invoker PS session with runspaces... but it doesn't feel good to me and probably has a lot of quirks. Even if we succed to do so, the history item does not have the same meaning on another context: eg. the history would say `Get-FileHash $filename` but we don't know the content of $filename.
So, we should first go for another item in the list: a gsudo-wrapper cmdlet (#39). The rationale for that is described on that issue, but the idea is to make elevation syntax feel more PS native. Once that one is coded, the `!!` can be implemented on that cmdlet as it can `Get-History` easily because the cmdlet runs in the same session as the invoker.

**Comment by oising** [comment]
the `psreadline` module maintains its own history list, and this module is default on every modern version of windows. get-history is ubiquitous, but has its own issues.

**Comment by majkinetor** [comment]
Using PSReadline is easy to do via function.

```
 function gsudo!! { 
   $c = cat (Get-PSReadLineOption).HistorySavePath | select -last 1 -Skip 1
   gsudo $c 
}
```

**Comment by gerardog** [comment]
On gsudo v1.0 you may experiment editing `gsudo.ps1` to:

```
if ($MyInvocation.Line -match "!!$")
{ 
	$c = Get-Content (Get-PSReadLineOption).HistorySavePath | Select-Object -last 1 -Skip 1
	gsudo $c
}
elseif($myinvocation.expectingInput) {
	$input | & gsudo.exe @args 
} 
else { 
	& gsudo.exe @args 
}
```

**Comment by mattcargile** [comment]
> > On gsudo v1.0 you may experiment editing `gsudo.ps1` to:
> > ```
> > if ($MyInvocation.Line -match "!!$")
> > { 
> > 	$c = Get-Content (Get-PSReadLineOption).HistorySavePath | Select-Object -last 1 -Skip 1
> > 	gsudo $c
> > }
> > elseif($myinvocation.expectingInput) {
> > 	$input | & gsudo.exe @args 
> > } 
> > else { 
> > 	& gsudo.exe @args 
> > }
> > ```
> 
> What would be the path of such a file?

It is located [here](https://github.com/gerardog/gsudo/tree/Feature.PwshSyntax/src/gsudo.extras). You'd have to download or clone it manually and pull it into your `$PROFILE` or the like. Additionally, if you are interested, please provide insight on Issue #39 to help future development in this space of the repo. There is a script `Invoke-gsudo.ps1` that is being worked on and this `!!` function could be incorporated in it.

**Comment by gerardog** [comment]
For reference, for this feature to work on PowerShell, you need to follow the instructions given in the [readme](https://github.com/gerardog/gsudo#bang-bang-): Which is: `import-module gsudoModule.psd1` in your `$profile`:

Please run the following, and it will do it for you:
```
Get-Command gsudoModule.psd1 | % { Write-Output "`nImport-Module `"$($_.Source)`"" | Add-Content $PROFILE }
```

**Comment by DigiOhhh** [comment]
Doesn't work for me:
```Error: Failed to find last invoked command (GetConsoleCommandHistoryLength==0)```

**Comment by gerardog** [comment]
@DigiOhhh: have you imported `gsudoModule` as my last comment said? (plus reloading your profile)

**Comment by DigiOhhh** [comment]
Yes, this is the content of my profile:
```
# Chocolatey profile
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"

if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}


Import-Module "C:\ProgramData\chocolatey\lib\gsudo\bin\gsudoModule.psd1"
```

**Comment by gerardog** [comment]
Please: check you gsudo version, if not `1.3.0` do `choco upgrade gsudo`.
Change your `$profile` for the new path `Import-Module 'C:\tools\gsudo\Current\gsudoModule.psd1'`
Then restart your consoles, then paste the results of:

    Get-Module gsudoModule | fl
    Get-Command gsudo | fl

**Comment by gerardog** [comment]
Should look like:
![image](https://user-images.githubusercontent.com/3901474/163689876-abc3664a-81bb-472d-97ee-4d62a8b1b9bf.png)

**Comment by DigiOhhh** [comment]
![image](https://user-images.githubusercontent.com/37815914/163690192-fcb8699d-4f26-4952-8b65-685fa5de9d1e.png)

Anyways I think I got it: `gsudo !!` works, but `sudo !!` doesn't

**Comment by gerardog** [comment]
Right, I´ve updated the readme recently:

> You can create a custom alias for gsudo or Invoke-gsudo, as you prefer: (add one of these lines to your $PROFILE)
> - `Set-Alias 'sudo' 'gsudo'` or
> - `Set-Alias 'sudo' 'Invoke-gsudo'`

The first one (`Set-Alias 'sudo' 'gsudo'`) is the one you should append to your profile

**Comment by DigiOhhh** [comment]
Works good! Thank you
