### ISSUE TITLE
CHOCOLATEY PACKAGE: (feature request) Don't add gsudo to the path and delete the gsudo.exe.ignore file

### ISSUE THREAD

**Issue by bcurran3** [gerardog/gsudo#47]
There's no need to add gsudo to the path in the Chocolatey package. If you delete the gsudo.exe.ignore a shim will be created in Chocolatey's bin folder which is already on the path. You can also remove the instruction to refreshenv as the environment won't need to change and gsudo will work instantly.

**Comment by gerardog** [comment]
Hi. What you are describing is exactly how the choco package worked originally. Unfortunatelly using a gsudo via a SHIM creates several issues, some of them can't even be fixed at gsudo or the shim itself such as #9 (Cmd/DosKey issue).

**Comment by gerardog** [comment]
Another Issue I encountered months ago and that I needed to re-test to confirm: When using Choco-Shim for gsudo: pressing CTRL-C kills the shim but keeps gsudo open. generating this weird scenario where pressing `<enter>` transitions from the elevated shell to the non-elevated one. (two processes actively reading input on the same console)

```
C:\ProgramData\chocolatey>gsudo
C:\ProgramData\chocolatey# ping 127.0.0.1 -t

Pinging 127.0.0.1 with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Min
imum =C:\ProgramData\chocolatey> 0ms, Maximum = 0ms, Average = 0ms
Control-C
^C
C:\ProgramData\chocolatey#
C:\ProgramData\chocolatey>
C:\ProgramData\chocolatey#
C:\ProgramData\chocolatey>
```
(see inconsitent command prompt at the end)

**Comment by gerardog** [comment]
Related to chocolatey/shimgen#32

**Comment by bcurran3** [comment]
BTW: I Just discovered gsudo and I want to say I've taking a shine to it and am using it daily now instead of sudo and elevate. I discovered that I can just run gsudo to switch to and stay with admin privileges is very nice. (No I haven't read the docs or anything other than install it after someone else said they use it.)

**Comment by bcurran3** [comment]
What other issues are there with it shimmed? I get the Ctrl-C one, but that's an upstream issue. Just wondering what the others are. Ultimately it's a minor issue, just seems to me it "should" be done the normal Chocolatey shim way.

**Comment by gerardog** [comment]
Relevant:
- Ctrl-C: This one is a blocker to me.
- Future feature #39 may require to add a pair of PowerShell ´.ps1´ files to the Path. They could be shimmed like Scoop does, but I don't think choco does that. And I'm 

No longer relevant:
- The Issue #9 I mentioned earlier looks like it's not a problem anymore, (as a side effect of the new default TokenSwitch mode 
in v0.7). It's a strange case where Cmd/Windows fails to bring the command history with the Up/Down arrows, and was triggered when using shims. (You can still reproduce it with `gsudo --attached` with a sim).

**Comment by ferventcoder** [comment]
> When using Choco-Shim for gsudo: pressing CTRL-C kills the shim but keeps gsudo open.

Commented on the shimgen issue, but this is opposite what https://github.com/chocolatey/shimgen/issues/32 is about. Folks are asking that Ctrl+C NOT kill the underlying process (gsudo in this case). I think it's likely there is something incompatible between how shimgen works and how gsudo works that prevents this from working properly and leaves gsudo open. It might be worth opening a separate issue on shimgen on related to just this.

**Comment by gerardog** [comment]
I am actually also interested in not killing the child process (gsudo or any other)! Not even after a delay. IMHO it's outside of the scope of the SHIM to kill it. If the inner process has a bug, hangs or does not responds to Ctrl-C appropriately is not the Shim responsibility to fix the problem. I would ask, what problem does killing the shim or the inner process on Ctrl-C solves? and could we address that in another way.
(shims of windows apps comes to my mind, not sure how Choco handles that, on gsudo I check if the app to launch [is a windows app](https://github.com/gerardog/gsudo/blob/d1b4abb3d069aaa1b5f06e6f9ecb7a1a83f689a4/src/gsudo/Helpers/ProcessFactory.cs#L100) and if true, it does not wait it to end.)

**Comment by ferventcoder** [comment]
@gerardog So basically you are thinking the shim should just ignore and forward the request?

Also, I recently heard of gsudo and I think it is exactly what I was looking for previously, fantastic work!

**Comment by gerardog** [comment]
Thanks! I appreciate it. And yes, IMHO just ignore and forward, same as gsudo does.

**Comment by gerardog** [comment]
Even if all shim issues are solved (which I haven't tested lately), but whats is being done for both #55 and #56 relies on having a `gsudo.sh` and `gsudo.ps1` folder in the path. Choco does not allows to shim those kind of files. (Scoop only shims the ps1) So it is unlikely that I could move forward with this suggestion. Sorry. 🙁
