### ISSUE TITLE
sudo-alias doesn't work

### ISSUE THREAD

**Issue by IskanderNovena** [gerardog/gsudo#48]
When typing in the 'sudo' alias, I get an error:
```
❯ sudo
Cannot find file at '..\lib\sudo\bin\sudo.cmd' (C:\ProgramData\chocolatey\lib\sudo\bin\sudo.cmd). This usually indicates a missing or moved file.
```

Install was done using `choco install gsudo`.
Initially I had another sudo-package installed. I removed both sudo and gsudo and re-installed gsudo, but I get the same result.

**Comment by gerardog** [comment]
This is not a bug in 'gsudo' but in the other `sudo` package.
When you uninstall that package, it leaves a `sudo.exe` file in your system.  like in a CMD as admin:

```
C:\>choco install sudo
(...)
C:\>choco uninstall sudo
(...)
C:\>choco install gsudo
(...)
C:\>where sudo                                    <-- Find wich "sudo" will run
C:\ProgramData\chocolatey\bin\Sudo.exe            <-- First result not gsudo
C:\ProgramData\chocolatey\lib\gsudo\bin\sudo.exe  <-- Second entry is gsudo but only the first one is run

C:\>del C:\ProgramData\chocolatey\bin\Sudo.exe
C:\>sudo 
gsudo v0.7
Copyright(c) 2019-2020 Gerardo Grignoli and GitHub contributors
```
Done! 

So, just open CMD as Admin and run **`DEL "C:\ProgramData\chocolatey\bin\Sudo.exe"`**
