### ISSUE TITLE
Run as TrustedInstaller

### ISSUE THREAD

**Issue by mikelei8291** [gerardog/gsudo#49]
Is it possible to add an option to run as TrustedInstaller?

**Comment by gerardog** [comment]
It [could be done](https://www.tiraniddo.dev/2017/08/the-art-of-becoming-trustedinstaller.html), but I don't want Microsoft to pull the plug and mark `gsudo` as virus, as it happened with jschicht/RunAsTI#9 😥

**Comment by gerardog** [comment]
I'm really sorry. Try NirSoft's [AdvancedRun](https://www.nirsoft.net/utils/advanced_run.html)

`choco install advancedrun`

![image](https://user-images.githubusercontent.com/3901474/87909044-ddba2080-ca3d-11ea-93b7-05c851ef5bc0.png)

![image](https://user-images.githubusercontent.com/3901474/87908901-9e8bcf80-ca3d-11ea-8a3f-b1c164fcf8ed.png)

**Comment by mikelei8291** [comment]
Thanks for the reply and solution. I wasn't aware of the problem that MS could mark it as a virus in Windows Defender as I disabled it completely.
