### ISSUE TITLE
Can't run `gsudo`, installed from chocolatey

### ISSUE THREAD

**Issue by grepcake** [gerardog/gsudo#50]
### Steps to reproduce:
  1. run shell as administrator
  2. `cinst gsudo`
  3. `gsudo`
  4. open non-elevated shell
  5. `gsudo`

### Observed behaviour:
  At step 3 I see a message that the shell is already elevated. At step 5 I see a message that `gsudo` is not recognized as a program.

### Expected behaviour:
  I can run a program with elevated privileges at step 5.

### My thoughts
  I have two users: one has administrator privileges, the other one doesn't. It appears that gsudo sets the PATH for the administrator user but not the system PATH (I looked at environment variables as the first and as the second user). Thus, the ordinary user can't access `gsudo`. 

  I guess, it should be possible to modify system PATH instead of the user local one?

**Comment by gerardog** [comment]
You got a point. But I have second thoughts on how this should be fixed.

- ✔ `scoop install scoop -g` OK. Installs in global directory and sets system path.
- ✔ `scoop install scoop`      OK. Installs in the current user directory and sets user path. Note scoop does not requires admin privileges so can install as non-admin.
- ❌ `choco install gsudo -g`  There is no such thing as `--global` in Chocolatey. It ignores `-g`/`--global`. Always installs in global directory but sets current user only path.
- ❌ `choco install gsudo` Installs in global directory but sets current user only path. Requires Admin privileges.

I think your proposal to change system path makes sense with CHOCO installer, plus document that users with separate admin and non-admin accounts can use `-g` on Scoop.

Thoughts?

**Comment by grepcake** [comment]
Thank you for an informed response!

It seems to me that `choco` is made to work like linux package managers work: it installs packages globally by default. Other packages seem to also be installed with that assumption in mind: they modify _system_ variables (e.g. `PATH`). I guess,  `gsudo` should follow that practice as well.

`scoop` has different semantics, since it installs packages locally by default, so current behaviour works well enough.

So, your suggested solution makes a lot of sense and it's the way to go.

**Comment by grepcake** [comment]
Thank you!
