### ISSUE TITLE
Unhandled Exception after CTRL+C

### ISSUE THREAD

**Issue by Schwitzd** [gerardog/gsudo#53]
Dear all, 

if you press CTRL+C during a loop command like "ping foo -t" I get the following error:
`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.`

thanks a lot
Daniel

**Comment by gerardog** [comment]
I finally understood the problem: the Ctrl-C Handler delegate is being garbage collected. 
Working on a fix.

**Comment by gerardog** [comment]
Fixed, you can test it on [this build](https://ci.appveyor.com/project/gerardog/gsudo/builds/34523256/artifacts) before the next release.

**Comment by Schwitzd** [comment]
Dear Gerardo,

sorry for the late answer but is working 👍
