### ISSUE TITLE
There should be a way to allow de-escalation of privelages

### ISSUE THREAD

**Issue by AngryCder** [gerardog/gsudo#59]
I think there should be a way for de-escalation as an additional feature

**Comment by gerardog** [comment]
There is one already! But it's almost hidden in the documentation.

> ## Usage
> 
> - `-i | --integrity {v}`**   Run command with a specific integrity level: `Low`, `Medium`, `MediumPlus`, `High` (default), `System`. 
**For example, use `Low` to launch a restricted process, or use `Medium` from an Admin/Elevated window to run without Admin rights.** 

Truth be told, `-i` changes both integrity level and token privileges. `-i high` is the common "elevation" and means high integrity level and current-user-max token privileges ( run 'whoami /priv' ), while '-i Medium' means Medum-IL (non-elevated) and non-admin privileges. 

So, from an elevated console you can: 
- `gsudo -i medium`
- `gsudo -i medium -n`
- `gsudo -i medium powershell -c Invoke-SomeThing`

Or you can use low integrity to restrict the process even more, but I haven't really found much that can be done with low integrity.
- `gsudo -i low`
