### ISSUE TITLE
Issue: language changes to english after gsudo

### ISSUE THREAD

**Issue by megapro17** [gerardog/gsudo#63]
## Issue Description

When i run gsudo my terminal changes language to english

## Steps to Reproduce
1. In powershell: run gsudo and accept uac, terminal now in english
2. In cmd even running `gsudo -v` is enough, accepting or declining uac also changes a language

## Screenshots
![image](https://user-images.githubusercontent.com/16743370/98714453-f4dc9f80-2399-11eb-877c-9ea58da70861.png)

## Context:
 - Windows version: 20H2
 - gsudo version: v0.7.2

**Comment by gerardog** [comment]
Can you please run `chcp` before and after running `gsudo` and share with me the results?

I think this is an unintended consequence of the #31 issue fix. Setting the console output encoding, seems to be [changing the console codepage](https://referencesource.microsoft.com/#mscorlib/system/console.cs,641). That issue is specific to gsudo's VT mode, which is disabled by default. I can move that fix to a more specific location such as the VTClientRenderer so it does not impact the 99.99% scenario.

**Comment by gerardog** [comment]
I've setup a virtual machine, installed language Russian and set regional settings to Russia, and finally got CMD localized.

`chcp` is not showing a codepage change, but I confirmed removing [this line](https://github.com/gerardog/gsudo/commit/d5cd2c0d937cc93ead535c96b1631d973b137b67#diff-ab44b95b5239a2d5cb5b4162f02c3410577c57c191042292b9d8c895b633c83aR19) fixes the issue, but also reverts that other fix.
Not sure how to properly fix both scenarios, but as I said above: VT-mode is experimental only (default mode is better in every way) so those who experiment with it may have to deal with this problem for the moment.

**Comment by megapro17** [comment]
> `chcp` is not showing a codepage change

Me too

Can I help with anything else?

**Comment by gerardog** [comment]
Yes. Could you please test the fix in your environment and confirm it's working? 

You can grab a build of the fix from here: https://ci.appveyor.com/project/gerardog/gsudo/builds/36257473/artifacts

**Comment by megapro17** [comment]
Sadly it crashes immediately 
```
Unhandled Exception: System.ComponentModel.Win32Exception: Invalid function
    in gsudo.Helpers.SymbolicLinkSupport.GetFinalPathName (String path)
    in gsudo.Helpers.SymbolicLinkSupport.ResolveSymbolicLink (String symLinkFullPath)
    in gsudo.Helpers.SymbolicLinkSupport.EnableAssemblyLoadFix ()
    in gsudo.Program. <Main> d__0.MoveNext ()
--- End of the stack trace from the previous location where the exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
    in gsudo.Program. <Main> ()
```

**Comment by megapro17** [comment]
Hm, moving to another location fixes the problem. I executed gsudo from root of R:/ (6gb ntfs partition, Imdisk ramdisk)

**Comment by gerardog** [comment]
I fixed that one as well. ([build](https://ci.appveyor.com/project/gerardog/gsudo/builds/36258281/artifacts))
Thanks!
