### ISSUE TITLE
gsudo in WinGet Package Manager?

### ISSUE THREAD

**Issue by matthewjdegarmo** [gerardog/gsudo#64]
It would be great to also install this from WinGet. Is that possible?

**Comment by gerardog** [comment]
Hi! Thanks for using gsudo and submitting the request.
This was requested as #52 before. I am waiting for WinGet to be able to install portable apps (microsoft/winget-cli#140). I haven't bought the idea to create and mantain an installer.

**Comment by matthewjdegarmo** [comment]
Great! Thanks! I didn't see the open issue.
