### ISSUE TITLE
bug in other launguage env

### ISSUE THREAD

**Issue by MasterOfStar** [gerardog/gsudo#67]
## Issue Description
gsudo changed my language in the shell.
It even changed the font after running it in powershell.
Resume normal after restarting the terminal.
## Steps to Reproduce
1.  run 'gsudo'
## Screenshots
![image](https://user-images.githubusercontent.com/21274896/102704556-f746e900-42b7-11eb-92c6-039a3cbfaa52.png)
![image](https://user-images.githubusercontent.com/21274896/102704567-10e83080-42b8-11eb-939b-48f390093447.png)

It even changed the font after running it in powershell：
before:
![image](https://user-images.githubusercontent.com/21274896/102704500-24df6280-42b7-11eb-8fc4-d38a6501e05f.png)
after:
![image](https://user-images.githubusercontent.com/21274896/102704542-ccf52b80-42b7-11eb-9423-51128a8acd2b.png)
![image](https://user-images.githubusercontent.com/21274896/102704600-8227e380-42b8-11eb-9d6b-29173425cf03.png)

**When I run the ```gsudo ping``` command the font is changed to Bitmap font, and when I just run ```gsudo -v``` the font is changed to console**
## Context:
 - Windows version: Windows10 20H2 19042.685
 - gsudo version:  gsudo 0.7.2

### All texts are translated from Chinese

**Comment by gerardog** [comment]
Thanks for your detailed report. Lools like this is the same issue as #63..
I will release the fix soon on v0.7.3, or you can test it now from this [link](https://ci.appveyor.com/project/gerardog/gsudo/builds/36258281/artifacts)

Thanks!

**Comment by gerardog** [comment]
Fixed in the just released v0.7.3.  Thanks
