### ISSUE TITLE
gsudo on Windows 7 x32  

### ISSUE THREAD

**Issue by lazna** [gerardog/gsudo#73]
testing batchfile with gsudo on some computer. Batch file run fine, gsudo work. Immediatelly after testrun, when batch cmd window is closed, trying to delete gsudo from desktop, but system complain: "the action could not by completed because the file is open in gsudo.exe". After few minutes gsudo.exe could be normaly deleted. W7/32bit

Is this known behavoiur?

**Comment by gerardog** [comment]
If you are using CacheMode=auto, then yes, it Is the "credentials cache", the elevated gsudo instance that makes further elevations without UAC prompt.
Use 'gsudo -k' to kill the cache. Or 'gsudo config cachemode disabled'

**Comment by lazna** [comment]
Will it work if append 'gsudo -k' at the end of batch file. Does it cachichg credentials but clear the cache at the end?

**Comment by gerardog** [comment]
Yes it will.
You can also use explicit `cache on` and `cache off` comands to have complete control within the batch file, try this:
```
gsudo cache on --loglevel none
If ERRORLEVEL 999 ECHO Elevation Failed EXIT /b 1
gsudo echo Do Elevated Stuff Here
gsudo cache off
```
This works with CacheMode in Auto or Explicit (default) mode.

**Comment by gerardog** [comment]
I got a Win7 VM and tested it. Just found out that the cache is not working on Windows 7 x32, for gsudo v0.7.3.
At least the elevation works.

So, for Windows 7:

Use `gsudo config cachemode disabled` to disable the credentials cache. (It doesnt work anyway, but this will avoid having a useless gsudo cache instance running.)
Use `gsudo config prompt "$p# "` to see a clean cmd prompt.

I'll see how these can be addressed in the future.

**Comment by gerardog** [comment]
I don't see much reasons to fix this issues for Windows 7.
Just document them in this issue, and let people work around as explained.
