### ISSUE TITLE
Issue: empty line when pipe to Out-null

### ISSUE THREAD

**Issue by alanlivio** [gerardog/gsudo#77]
## Issue Description

I want to call a command from gsudo without receive any output. Although pip to Out-null, the gsudo put an empty line.

## Steps to Reproduce
For instance, we may reproduce with Get-ChildItem 
`` powershell
gsudo Get-ChildItem |Out-null
```

## Screenshots
<!-- You can capture a screenshot with Ctrl+PrintScreen and paste it here with Ctrl-V. -->
<!-- Really helps if you use the "gsudo --debug" flag: For example instead of "gsudo notepad" do "gsudo --debug notepad"  -->
![image](https://user-images.githubusercontent.com/604808/106611569-e4763400-6546-11eb-8ba5-df75879d6397.png)


## Context:
 - Windows version: 10.0.19042.0
 - gsudo version:     gsudo v0.7.3

**Comment by gerardog** [comment]
I am not able to reproduce this issue. In my case the command gave the same result with or without gsudo.
![image](https://user-images.githubusercontent.com/3901474/106649175-f7e9c500-656f-11eb-9519-925e3914dba4.png)

Do you have any idea how can I reproduce the issue? 
What powershell version are you running?

**Comment by alanlivio** [comment]
I remember that, I was using a module called Get-ChildItemColor.
Then to reproduce the error,  run:
```powershell
Import-Module Get-ChildItemColor 
gsudo Get-ChildItem| Out-Null
````
After remove, the module (``Import-Module Get-ChildItemColor ```) the endline is gone.

Howoever, the trick part is that the module inserts the end line not just in Get-ChildItem calls but in other as well. 
For instance it adds the lines into the gsudo help (screenshot bellow). To reproduce that, run:
```powershell
Import-Module Get-ChildItemColor 
gsudo  --help | Out-Null
````


![image](https://user-images.githubusercontent.com/604808/106659053-fd014100-657c-11eb-9f19-fd8612d0d750.png)

**Comment by gerardog** [comment]
Thanks. So this is not a problem in gsudo. This is caused by Get-ChildItemColor module and needs to be fixed there. There is nothing gsudo could or should do to fix it.

![image](https://user-images.githubusercontent.com/3901474/106663423-764f6280-6582-11eb-9340-dc3916e9cd8e.png)

You may want to create a new issue on joonro/Get-ChildItemColor repo or follow up on this issue which looks related joonro/Get-ChildItemColor#36.

**Comment by gerardog** [comment]
I quickly went thru `Get-ChildItemColor.psm1` [here](https://github.com/joonro/Get-ChildItemColor/blob/v2.1.1/src/Get-ChildItemColor.psm1#L205) and found that if you set 
```` powershell
$Global:GetChildItemColorVerticalSpace = 0
````
... on your session, or on your profile, the problem goes away.

**Comment by alanlivio** [comment]
Thanks for the feedback.
