### ISSUE TITLE
Question: Can I run as some other user?

### ISSUE THREAD

**Issue by MikeDombo** [gerardog/gsudo#79]
Hi,
Based on the command line options in the readme I fear that the answer is no, but is it possible to do `gsudo -u myOtherAccount <command>`, like I would do with sudo on linux? If it is not possible with gsudo, do you know if it is possible at all on Windows to run a command as another user without their password, assuming that I'm running with admin privileges already?

**Comment by gerardog** [comment]
Hi,
gsudo does not support to run as a different user at this time. Windows security is a little tricky regarding this. Let's explore the possibilities here. 

* RunAsUser approach: 
If you use the CreateProcess's RunAsUser verb you can specify a username and password, same effect as shift+right click on a shortcut, then "run as different user" 

![image](https://user-images.githubusercontent.com/3901474/108940804-c45fff00-7632-11eb-8282-e87a900c2186.png)

You can trigger this using this powershell line:
`Start-Process cmd.exe -verb RunAsUser`

![image](https://user-images.githubusercontent.com/3901474/108940312-e4db8980-7631-11eb-9794-31838927d756.png)

Or with PSExec / PAExec.

First thing is, you must know the username and password.
The second thing is, even if the username is a local admin, the process won't be elevated. I.E. The new process will run as that user but without admin privileges, at least until that user tries to elevate, and then a second popup (this time in the secure desktop/screen dim) needs to appear.

I was thinking for workarounds for this double pop-up, or whatever that would make the 'run as different user' scenario not something the users won't hate or barely tolerate. I eventually gave up.

* A service or a Scheduled task:

You can create a windows service (tricky) or a scheduled task (easy) and then specify the username and password it should use. You put the password ONCE. Then, any other at any moment can start the scheduled task, which will run the process as the special user. Check "Run only when the user is logged on" if you want to interact with this task.

* Acting as Part of the operating system.

If you impersonate SYSTEM you get the SeTcbPrivilege ("Act as part of the operating system") means your code is part of the Trusted Computer Base.  gsudo use this in some situations. But also means you theoretically could create your own login tokens. This is a complex topic and I am not a subject expert. I am not sure this means it could simulate another user's login.

**Comment by MikeDombo** [comment]
Thanks for the pointers! I'll look into those options.

Thanks for the help

**Comment by gerardog** [comment]
You are welcome. Let me know your progress, looks like an interesting project.
