### ISSUE TITLE
It seems not well work with netsh

### ISSUE THREAD

**Issue by DH-Illidan** [gerardog/gsudo#81]
## Issue Description

I want to config my static ip address in an evaluated mode, but it will activate my wsl shell, and finally failed.

## Screenshots
![image](https://user-images.githubusercontent.com/55729509/110060679-407be480-7da1-11eb-8319-4910251f0b29.png)

This is what I saw after I type "exit" manually.
![image](https://user-images.githubusercontent.com/55729509/110061058-d9aafb00-7da1-11eb-92d6-95edc40432cb.png)

## Context:
windows version: 19042.844
gsudo version: latest

**Comment by gerardog** [comment]
Hi. Yes, using gsudo on Powershell has some limitations at the moment, specially when using quotes.

Please use quotes as described in the [home](https://github.com/gerardog/gsudo#usage-from-powershell--powershell-core):
```
# On strings enclosed in single quotation marks ('), escape " with \"
$hash = gsudo '(Get-FileHash \"C:\My Secret.txt\").Hash'
# For variable substitutions, use double-quoted strings with single-quotation marks inside
$hash = gsudo "(Get-FileHash '$file' -Algorithm $algorithm).Hash"
# or escape " with \""
$hash = gsudo "(Get-FileHash \""$file\"" -Algorithm $algorithm).Hash"
```

So, try it like this:
`gsudo netsh 'interface ip address name=\"vEthernet....\" address=....'`

The intent to improve the syntax is part of #39.
