### ISSUE TITLE
gsudo v0.7.3 Signing certificate has expired

### ISSUE THREAD

**Issue by rfay** [gerardog/gsudo#82]
## Issue Description

Thanks so much for pointing this project out [on twitter](https://twitter.com/gerardo_gr/status/1369295765206667267)

Doing a quick check everything seemed OK. But I note that the signing certificate you're using has expired, at least the one that was used for v0.7.3

<img width="404" alt="Cursor_and_rfay-win10pro" src="https://user-images.githubusercontent.com/112444/110496226-85aa5a00-80b2-11eb-98ff-c2cebc7a88b8.png">

Time for a new cert and new release probably.

**Comment by gerardog** [comment]
You are right, the certificate has expired, but it wasn't expired when I published the last release. It has an embedded timestamp that you can check as well. If it were expired at that time, Certum Cloud Signing would have blocked the signing. You can check the UAC popup, that shows the digital signature as considered valid to Windows, with no warnings at all, meaning the signing is correct, no matter it ocurred in the past. 
BTW, I've already purchased a renewal which I will use for the next release. That will happen whenever a new set of features is ready!
Thanks.-
