### ISSUE TITLE
Question: How to switch back from --system ?

### ISSUE THREAD

**Issue by compwiz32** [gerardog/gsudo#83]
Maybe I am missing something obvious... i apologize in advance if I am.... 

If I run `gsudo -s` and switch to system context, I do not see a way to switch back from system to my user id (elevated or no-elevated). I have to close the session and re-launch or start another tab in Windows Terminal. 

Did I miss the option to switch back to my user id?

**Comment by gerardog** [comment]
Hi!
Short answer: type ‘exit‘ then press enter.
Long version: when gsudo is called from a command prompt (cmd.exe) it launches another (child) cmd.exe with different permissions/elevated. To return to the previous level, just end the new process typing 'exit'.

**Comment by compwiz32** [comment]
would you be ok if I submitted a PR to update the readme to add the above as an example / special case?

**Comment by gerardog** [comment]
Sure, all colaboration is welcomed! Just keep in mind that I forgot to explain this in the docs because this is not a special case. This is a part of the usual sudo flow and how the original unix/linux sudo works. I incorrectly assumed all the audience was familiar with this concept.
