### ISSUE TITLE
How do I remove the sudo alias

### ISSUE THREAD

**Issue by fabriciopg** [gerardog/gsudo#84]
I had already another sudo app installed before gsudo
I´d like to have the option to choose which one to use.
Reading the documentation here I noticed that an alias is created.
How this can be deleted ?

**Comment by gerardog** [comment]
Hi!
Open a command prompt as admin.
Type `where sudo` to get a list of apps that match `sudo`. The first one is the one that is ran when you execute sudo, and the rest is ignored.
It should be gsudo's sudo alias. If so, type `del <full path>` like:

```
C:\>where sudo

C:\ProgramData\chocolatey\lib\gsudo\bin\sudo.exe
C:\Users\gerar\scoop\shims\sudo
C:\Users\gerar\scoop\shims\sudo.cmd

C:\>del "C:\ProgramData\chocolatey\lib\gsudo\bin\sudo.exe"
```
