### ISSUE TITLE
Issue: When running gsudo through terminal/cmd it doesn't auto-focus on the UAC Prompt

### ISSUE THREAD

**Issue by fabis94** [gerardog/gsudo#85]
## Issue Description

When running gsudo through terminal/cmd it doesn't auto-focus on the UAC Prompt. This is very annoying because you have to move your mouse and click on "Yes" instead of being able to just press Alt + Y like you would be able to if you'd be focusing on the prompt.

## Steps to Reproduce
Doesn't matter if I use Cmd or Terminal, if I write `gsudo whatever` the prompt will appear, but won't be focused so Alt + Y won't accept it.

## Context:
 - Windows version: Windows 10 Pro 20H2 OS Build 19042.962
 - gsudo version: gsudo v0.7.3

**Comment by gerardog** [comment]
Hi, thanks for the feedback. Do you have UAC set up on "Do not dim"?

![image](https://user-images.githubusercontent.com/3901474/115946661-2bfec300-a499-11eb-8638-4143e19e40b3.png)

If so, please press "Win+R", and run regedit. Do you see the same problem?

I do and it looks like a problem with Windows UAC itself, when set in "Do not dim" mode. 
I created feedback using Feedback Hub. Please upvote: https://aka.ms/AAc1gmt

Also may be worth to keep an eye on this issue, microsoft/PowerToys#4933. To me, it looks like the same issue.

BTW, I tested it on gsudo and the call to CreateProcess hangs until the UAC popup is either accepted or dismissed. Meaning that when it happens, I do not have a an elevated process ID or hWnd yet, so I can't trick to focus the UAC popup window. It is unknown to me.

**Comment by fabis94** [comment]
Yea I've got Do not dim on. I can't upvote your feedback tho, it says "Your account doesn't have access to this feedback"

**Comment by gerardog** [comment]
I'm closing this, as it is rooted in Windows and I doubt there is anything I can think of to fix it. Refer to the Powertoys issue microsoft/PowerToys#4933 for a response from microsoft, given that my "feedback hub" ticket was "received" but I probably wont get a response there.

**Comment by gerardog** [comment]
Yeah, it's microsoft's fault, but they will **never ever** fix it. I'm using UAC with no don't dim these days, and it is annoying.

**Comment by gerardog** [comment]
I apologize @fabis94 for not listening you. This will ship in the next release.
