### ISSUE TITLE
Issue: gsudo does not show stdout/err

### ISSUE THREAD

**Issue by KUGA2** [gerardog/gsudo#89]
## Issue Description

In every terminal i got (git bash, cmd, powershell) with or without windows terminal, it does not show the stdout (or stderr) when i run a command with gsudo.

I am not completely sure, but I think the command itself works.

## Steps to Reproduce
1.  open cmd
2. run "dir" - output is shown
3. run "gsudo dir" - no output is shown

## Screenshots
![image](https://user-images.githubusercontent.com/10581931/123399805-5823e680-d5a5-11eb-9c5d-44554e37d7b3.png)

## Context:
 - Windows version: 20H2, 19042.1052
 - gsudo version: v0.7.3 (choco package)

**Comment by gerardog** [comment]
Hi, that is an interesting behaviour. Please run the following and paste the results:

```
where gsudo 
gsudo -v
gsudo --debug dir
```

**Comment by gerardog** [comment]
Just realized this may be related to some antivirus engines flagging gsudo as unsafe.

**Comment by KUGA2** [comment]
```
D:\git>where gsudo
C:\ProgramData\chocolatey\lib\gsudo\bin\gsudo.exe

D:\git>gsudo -v
gsudo v0.7.3
Copyright(c) 2019-2020 Gerardo Grignoli and GitHub contributors

D:\git>gsudo --debug dir
Debug: IsWindowsApp("C:\WINDOWS\system32\cmd.exe") = False ("C:\WINDOWS\system32\cmd.exe")
Debug: Command to run: C:\WINDOWS\system32\cmd.exe /c dir
Debug: Using Console mode TokenSwitch
Debug: CreateProcessAsUser: C:\WINDOWS\system32\cmd.exe /c dir
Debug: Elevating process: C:\ProgramData\chocolatey\lib\gsudo\bin\gsudo.exe --debug gsudoelevate --pid 9764
Debug: Elevated instance started.
```
And during debug run, there shortly is a separate screen. I managed to screenshot it:
![image](https://user-images.githubusercontent.com/10581931/123434369-af897d00-d5cc-11eb-8c80-99cabe306eb0.png)

Yes, my company is using Sophos antivirus. If this is the culprit, I will probably not be able to help solving this.. Sophos is locked by our IT and I cannot see or change any settings. There is no entry in Sophos log.

**Comment by gerardog** [comment]
Now I can tell your AV is not blocking the execution of gsudo. Nonetheless, creating the token fails with "Zugriff verweigert" ("Access Denied"). At this point I don't know why that is happening. But at least I can provide a workaround. 

Run: `gsudo config ForceAttachedConsole true` 

That will fall back to the previous elevation scheme. The bad part is that you wont be able to capture gsudo output as in `gsudo dir > outputfile`. But, everything else should work.

**Comment by KUGA2** [comment]
The workaround works. Is it persistent through terminals and reboots?
Then I can live with the limitation, i guess.

Maybe you can figure it out some time in the future :)

**Comment by gerardog** [comment]
Yes, it is persistent for reboots and terminals until you do `gsudo config ForceAttachedConsole false`.

Maybe if you occasionally use another german windows box you could see if the problem is related to your OS language, or not. 

Thanks!
