### ISSUE TITLE
Cache for current session only

### ISSUE THREAD

**Issue by felipecrs** [gerardog/gsudo#95]
The `sudo` on Linux has this behavior: it only asks for password for the first time in a shell session.

I believe if it's possible, this would be a better way to handle caching of UAC, as it would be guaranteed not to ask for UAC for the entire script, and malicious processes could not take advantage of this caching as it would only be available for the current shell process.

I'm just bringing this for discussion, but I'm thinking on something like:

1. `gsudo` discovers the PID of the program which invoked it.
2. `gsudo` starts a caching which would only be valid for that PID.
3. When that PID closes, `gsudo` would stop the caching (is this kind of hook possible?).

**Comment by gerardog** [comment]
Hi Felipe,
I am confussed: gsudo already has a credentials cache... And it works exactly as you described!

Cache default mode is explicit: User must explicitly start a cache session with `gsudo cache on`, for the invoker pid only.

You (and I) probable want it to behave like linux. So set cachemode=auto using `gsudo config cachemode auto`. Then your first gsudo call shows a UAC and starts a cache session, so you can elevate again.

In every case, the cache closes if the parent process closes. you can also do 'gsudo cache on -pid 0' to whitelist all processes.

Please take a look at how the cache [is supposed to work](https://github.com/gerardog/gsudo#credentials-cache). And let me know if it does for you. There may be a bug in regarding the cache. Are you elevating from Cmd? Powershell? WSL? 
(To be honest, I noticed the cache doesn't work from git-bash/MinGW/cygwin. maybe it is issue)

Please let me know. Thanks

**Comment by gerardog** [comment]
Or maybe you tried to enable cachemode=auto, but it threw an error. There is a bug if you installed gsudo v0.7.3 via winget: #93

The workaround is: open cmd as admin the regular way, then run `gsudo config cachemode auto`

**Comment by felipecrs** [comment]
You are absolutely right. My bad, sorry for the confusion.
