### ISSUE TITLE
Issue: Error when openning cmd.exe in Windows Terminal

### ISSUE THREAD

**Issue by YataoWang** [gerardog/gsudo#96]
Open the cmd.exe in Windows Terminal, the following error happens,
```
error 0x80070002 when launching `gsude.exe C:\Windows\System32\cmd.exe
```
I make sure that the gsude.exe and cmd.exe were added in my path environment.

The command of Windows Terminal tab is `gsude.exe C:\\Windows\\System32\\cmd.exe`

The gsudo.exe version is `v0.7.3`
The Windows version is `21H1 (OS Build 19043.1110)`

**Comment by gerardog** [comment]
Looks like a typo: `error when launching `gsude.exe`. It should be `gsudo` not `gsude` 😊

**Comment by gerardog** [comment]
Also, let me express my opinion regarding WT+gsudo. People is used to having an `elevated command prompt` profile and that the transition between unelevated and elevated is impossible. So they use gsudo to launch an elevated command prompt.

Also, I recommend just call `gsudo` whenever you need to elevate. Even prepend to the command. There is no right or wrong, just a matter of personal taste.

**Comment by YataoWang** [comment]
> Looks like a typo: `error when launching 'gsude.exe'`. It should be `gsudo` not `gsude` 😊

Oops. Thanks for pointing it out. It's my mistake....
