### ISSUE TITLE
Error on first time run after upgrading ("Unauthorized")

### ISSUE THREAD

**Issue by lazna** [gerardog/gsudo#99]
Performing gsudo start without parameters but got error msg:

```
c:\Scripts>c:\utils\gsudo.exe
Unauthorized.Error: Failed to substitute token. Connection from server lost.
```
than run with help parameter

`c:\Scripts>c:\utils\gsudo.exe -h `

this give me help screen OK. And than run witout parameter again

`c:\Scripts>c:\utils\gsudo.exe`

and it start OK now. No other actions performed. Microsoft Windows [Version 10.0.19042.1165] 64bit

**Comment by gerardog** [comment]
You probably upgraded to a new gsudo version, but with an active cache session already running using the previous gsudo version. 

When the elevated cache (eg `C:\Users\Myself\scoop\apps\gsudo\0.7.3\gsudo.exe`) detects a connection from a different EXE file ( `C:\Users\Myself\scoop\apps\gsudo\1.0.1\gsudo.exe` ) it assumes it may be a hack attempt and a) throws unauthorized, b) closes the elevated cache (preventing other hack attempts, also making this message not happening again).

**Comment by gerardog** [comment]
Nonetheless this is bad user experience, maybe I could...
a) invalidate active cache sessions on upgrade.
b) show nicer error messages.
